<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Category extends \AppBundle\Entity\Category implements \Doctrine\Persistence\Proxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
        __clone as private __doClone;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".'AppBundle\\Domain\\Model\\CategoryEntityModel'."\0".'existingElementsSetting' => ['AppBundle\\Domain\\Model\\CategoryEntityModel', 'existingElementsSetting', null],
        "\0".parent::class."\0".'approval' => [parent::class, 'approval', null],
        "\0".parent::class."\0".'attributeModule' => [parent::class, 'attributeModule', null],
        "\0".parent::class."\0".'children' => [parent::class, 'children', null],
        "\0".parent::class."\0".'created' => [parent::class, 'created', null],
        "\0".parent::class."\0".'deleted' => [parent::class, 'deleted', null],
        "\0".parent::class."\0".'elements' => [parent::class, 'elements', null],
        "\0".parent::class."\0".'favoredBy' => [parent::class, 'favoredBy', null],
        "\0".parent::class."\0".'groups' => [parent::class, 'groups', null],
        "\0".parent::class."\0".'hidden' => [parent::class, 'hidden', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'internal' => [parent::class, 'internal', null],
        "\0".parent::class."\0".'name' => [parent::class, 'name', null],
        "\0".parent::class."\0".'newUntil' => [parent::class, 'newUntil', null],
        "\0".parent::class."\0".'openInNewWindow' => [parent::class, 'openInNewWindow', null],
        "\0".parent::class."\0".'parent' => [parent::class, 'parent', null],
        "\0".parent::class."\0".'position' => [parent::class, 'position', null],
        "\0".parent::class."\0".'positionGlobal' => [parent::class, 'positionGlobal', null],
        "\0".parent::class."\0".'public' => [parent::class, 'public', null],
        "\0".parent::class."\0".'relatedCategories' => [parent::class, 'relatedCategories', null],
        "\0".parent::class."\0".'relatedCategory' => [parent::class, 'relatedCategory', null],
        "\0".parent::class."\0".'seenByUsersWithoutGroup' => [parent::class, 'seenByUsersWithoutGroup', null],
        "\0".parent::class."\0".'slug' => [parent::class, 'slug', null],
        "\0".parent::class."\0".'space' => [parent::class, 'space', null],
        "\0".parent::class."\0".'translations' => [parent::class, 'translations', null],
        "\0".parent::class."\0".'type' => [parent::class, 'type', null],
        "\0".parent::class."\0".'updated' => [parent::class, 'updated', null],
        "\0".parent::class."\0".'url' => [parent::class, 'url', null],
        'approval' => [parent::class, 'approval', null],
        'attributeModule' => [parent::class, 'attributeModule', null],
        'children' => [parent::class, 'children', null],
        'created' => [parent::class, 'created', null],
        'deleted' => [parent::class, 'deleted', null],
        'elements' => [parent::class, 'elements', null],
        'existingElementsSetting' => ['AppBundle\\Domain\\Model\\CategoryEntityModel', 'existingElementsSetting', null],
        'favoredBy' => [parent::class, 'favoredBy', null],
        'groups' => [parent::class, 'groups', null],
        'hidden' => [parent::class, 'hidden', null],
        'id' => [parent::class, 'id', null],
        'internal' => [parent::class, 'internal', null],
        'name' => [parent::class, 'name', null],
        'newUntil' => [parent::class, 'newUntil', null],
        'openInNewWindow' => [parent::class, 'openInNewWindow', null],
        'parent' => [parent::class, 'parent', null],
        'position' => [parent::class, 'position', null],
        'positionGlobal' => [parent::class, 'positionGlobal', null],
        'public' => [parent::class, 'public', null],
        'relatedCategories' => [parent::class, 'relatedCategories', null],
        'relatedCategory' => [parent::class, 'relatedCategory', null],
        'seenByUsersWithoutGroup' => [parent::class, 'seenByUsersWithoutGroup', null],
        'slug' => [parent::class, 'slug', null],
        'space' => [parent::class, 'space', null],
        'translations' => [parent::class, 'translations', null],
        'type' => [parent::class, 'type', null],
        'updated' => [parent::class, 'updated', null],
        'url' => [parent::class, 'url', null],
    ];

    /**
     * @internal
     */
    public bool $__isCloning = false;

    public function __construct(?\Closure $initializer = null)
    {
        self::createLazyGhost($initializer, [
            "\0".'AppBundle\\Domain\\Model\\CategoryEntityModel'."\0".'existingElementsSetting' => true,
            "\0".parent::class."\0".'id' => true,
            '__isCloning' => true,
        ], $this);
    }

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __clone()
    {
        $this->__isCloning = true;

        try {
            $this->__doClone();
        } finally {
            $this->__isCloning = false;
        }
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"], $properties['__isCloning']);

        return $properties;
    }
}
