when@dev:
    framework:
        session:
            handler_id: session.handler.native_file
            save_path: '%env(DEV_FRAMEWORK_SESSION_SAVE_PATH)%'

    maker:
        root_namespace: 'AppBundle'

    web_profiler:
        excluded_ajax_paths: '^/((index|app(_[\w]+)?)\.php/)?_wdt|\/feature\/metrics'

when@test:
    framework:
        mailer:
            dsn: 'null://null'
        session:
            handler_id: 'session.handler.native_file'
            save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    parameters:
        locale: de
    services:
        Symfony\Contracts\HttpClient\HttpClientInterface:
            public: true
            alias: .debug.http_client

doctrine_migrations:
    migrations_paths:
        'Application\Migrations': '@AppBundle/Migrations'
    organize_migrations: 'BY_YEAR'
    storage:
        table_storage:
            table_name: 'migration_versions'

framework:
    csrf_protection: ~
    default_locale: '%env(string:APP_LOCALE)%'
    mailer:
        dsn: '%env(MAILER_URL)%'
        envelope:
            sender: '%env(MAILER_SENDER)%'

httplug:
    clients:
        default:
            factory: 'httplug.factory.guzzle7'
            config:
                timeout: "%env(int:OAUTH_TIMEOUT)%"
                verify: "%env(bool:OAUTH_VERIFY_SSL)%"

hwi_oauth:
    firewall_name: main
    connect:
        confirmation: false
    resource_owners:
        oauth:
            type: oauth2
            class: AppBundle\Security\OAuth2ResourceOwner
            client_id: '%env(OAUTH_CUSTOM_CLIENT_ID)%'
            client_secret: '%env(OAUTH_CUSTOM_CLIENT_SECRET)%'
            access_token_url: '%env(OAUTH_CUSTOM_URL_ACCESS_TOKEN)%'
            authorization_url: '%env(OAUTH_CUSTOM_URL_AUTHORIZATION)%'
            infos_url: '%env(OAUTH_CUSTOM_URL_INFOS)%'
            scope: 'user:email'
            user_response_class: HWI\Bundle\OAuthBundle\OAuth\Response\PathUserResponse
            paths:
                identifier: id
                nickname: username
                realname: displayname
        azure:
            type: azure
            client_id: '%env(OAUTH_AZURE_CLIENT_ID)%'
            client_secret: '%env(OAUTH_AZURE_CLIENT_SECRET)%'
            access_token_url: '%env(OAUTH_AZURE_URL_ACCESS_TOKEN)%'
            authorization_url: '%env(OAUTH_AZURE_URL_AUTHORIZATION)%'
            scope: '%env(OAUTH_AZURE_OPTION_SCOPE)%'
            options:
                application: common
        okta:
            type: oauth2
            class: AppBundle\Security\OAuth2ResourceOwner
            client_id: '%env(OAUTH_OKTA_CLIENT_ID)%'
            client_secret: '%env(OAUTH_OKTA_CLIENT_SECRET)%'
            access_token_url: '%env(OAUTH_OKTA_URL_ACCESS_TOKEN)%'
            authorization_url: '%env(OAUTH_OKTA_URL_AUTHORIZATION)%'
            infos_url: '%env(OAUTH_OKTA_URL_INFOS)%'
            scope: 'openid email profile'
            options:
                csrf: true
            user_response_class: HWI\Bundle\OAuthBundle\OAuth\Response\PathUserResponse
            paths:
                identifier: sub
                nickname: email
                email: email
                realname: [ "given_name", "family_name" ]
                firstname: given_name
                lastname: family_name

knp_menu:
    twig:
        template: '@App/menu.html.twig'

knp_paginator:
    template:
        pagination: '@KnpPaginator/Pagination/twitter_bootstrap_v4_pagination.html.twig'

parameters:
    hwi_oauth.connect.registration_form: ''

security:
    role_hierarchy:
        ROLE_EDITOR: ROLE_USER
        ROLE_ADMIN: [ ROLE_USER, ROLE_EDITOR ]
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
            algorithm: 'auto'
            migrate_from:
                - sha512
    providers:
        app:
            id: AppBundle\Security\UserProvider
    firewalls:
        public:
            pattern: ^/(_wdt|_profiler|asset)
            security: false
        main:
            access_token:
                token_handler: AppBundle\Security\AccessTokenHandler
                token_extractors: query_string
            entry_point: form_login
            switch_user: { role: CAN_SWITCH_USER }
            form_login:
                check_path: /login_check
                enable_csrf: true
                login_path: /login
                success_handler: AppBundle\Security\RedirectAfterLoginHandler
            logout:
                path: app_user_security_logout
            provider: app
            oauth:
                resource_owners:
                    oauth: '/login/check-oauth'
                    azure: '/login/check-azure'
                    okta: '/login/check-okta'
                login_path: /login
                failure_path: /login
                oauth_user_provider:
                    service: AppBundle\Component\Security\OAuthProvider
        login:
            pattern: ^/login$
            security: false
    access_control:
        - { path: ^/, roles: PUBLIC_ACCESS }
        - { path: ^/settings, role: ROLE_EDITOR }
        - { path: ^/admin, role: ROLE_ADMIN }

twig:
    form_themes: [ '@App/_components/form/default.html.twig' ]
    globals:
        debug_javascript: '%env(bool:APP_DEBUG_JAVASCRIPT)%'
