<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ILRxu9hService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.iLRxu9h' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.iLRxu9h'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'news' => ['privates', '.errored..service_locator.iLRxu9h.AppBundle\\Entity\\Setting\\Feature\\News', NULL, 'Cannot autowire service ".service_locator.iLRxu9h": it needs an instance of "AppBundle\\Entity\\Setting\\Feature\\News" but this type has been excluded in "config/services.yaml".'],
        ], [
            'news' => 'AppBundle\\Entity\\Setting\\Feature\\News',
        ]);
    }
}
