<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_5k_PWdvService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.5k.PWdv' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.5k.PWdv'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'qrCode' => ['privates', '.errored..service_locator.5k.PWdv.AppBundle\\Entity\\myHub\\QrCode', NULL, 'Cannot autowire service ".service_locator.5k.PWdv": it needs an instance of "AppBundle\\Entity\\myHub\\QrCode" but this type has been excluded in "config/services.yaml".'],
        ], [
            'qrCode' => 'AppBundle\\Entity\\myHub\\QrCode',
        ]);
    }
}
