<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NOoSwRService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.nOoSw_R' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.nOoSw_R'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'shortLink' => ['privates', '.errored..service_locator.nOoSw_R.AppBundle\\Entity\\ShortLink', NULL, 'Cannot autowire service ".service_locator.nOoSw_R": it needs an instance of "AppBundle\\Entity\\ShortLink" but this type has been excluded in "config/services.yaml".'],
        ], [
            'shortLink' => 'AppBundle\\Entity\\ShortLink',
        ]);
    }
}
