<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_M9u3xj3Service extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.M9u3xj3' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.M9u3xj3'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'chapterTeaserItem' => ['privates', '.errored..service_locator.M9u3xj3.AppBundle\\Entity\\SmartBlock\\ChapterTeaserItem', NULL, 'Cannot autowire service ".service_locator.M9u3xj3": it needs an instance of "AppBundle\\Entity\\SmartBlock\\ChapterTeaserItem" but this type has been excluded in "config/services.yaml".'],
            'element' => ['privates', '.errored..service_locator.M9u3xj3.AppBundle\\Entity\\Element', NULL, 'Cannot autowire service ".service_locator.M9u3xj3": it needs an instance of "AppBundle\\Entity\\Element" but this type has been excluded in "config/services.yaml".'],
        ], [
            'chapterTeaserItem' => 'AppBundle\\Entity\\SmartBlock\\ChapterTeaserItem',
            'element' => 'AppBundle\\Entity\\Element',
        ]);
    }
}
