<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_2Q4aKDService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.2_q4aKD' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.2_q4aKD'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'eyeCatcher' => ['privates', '.errored..service_locator.2_q4aKD.AppBundle\\Entity\\SmartTool\\Inspiration\\EyeCatcher', NULL, 'Cannot autowire service ".service_locator.2_q4aKD": it needs an instance of "AppBundle\\Entity\\SmartTool\\Inspiration\\EyeCatcher" but this type has been excluded in "config/services.yaml".'],
        ], [
            'eyeCatcher' => 'AppBundle\\Entity\\SmartTool\\Inspiration\\EyeCatcher',
        ]);
    }
}
