<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_94r7W79Service extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.94r7W79' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.94r7W79'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'share' => ['privates', '.errored..service_locator.94r7W79.AppBundle\\Entity\\Share', NULL, 'Cannot autowire service ".service_locator.94r7W79": it needs an instance of "AppBundle\\Entity\\Share" but this type has been excluded in "config/services.yaml".'],
        ], [
            'share' => 'AppBundle\\Entity\\Share',
        ]);
    }
}
