<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NfU5iCmService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.nfU5iCm' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.nfU5iCm'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'category' => ['privates', '.errored..service_locator.nfU5iCm.AppBundle\\Entity\\Setting\\Feature\\NewsCategory', NULL, 'Cannot autowire service ".service_locator.nfU5iCm": it needs an instance of "AppBundle\\Entity\\Setting\\Feature\\NewsCategory" but this type has been excluded in "config/services.yaml".'],
        ], [
            'category' => 'AppBundle\\Entity\\Setting\\Feature\\NewsCategory',
        ]);
    }
}
