<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_A9g5xlkService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.a9g5xlk' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.a9g5xlk'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'otherUser' => ['privates', '.errored..service_locator.a9g5xlk.AppBundle\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.a9g5xlk": it needs an instance of "AppBundle\\Entity\\User" but this type has been excluded in "config/services.yaml".'],
        ], [
            'otherUser' => 'AppBundle\\Entity\\User',
        ]);
    }
}
