<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NCpT9q5Service extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.NCpT9q5' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.NCpT9q5'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'bookmark' => ['privates', '.errored..service_locator.NCpT9q5.AppBundle\\Entity\\User\\Bookmark', NULL, 'Cannot autowire service ".service_locator.NCpT9q5": it needs an instance of "AppBundle\\Entity\\User\\Bookmark" but this type has been excluded in "config/services.yaml".'],
        ], [
            'bookmark' => 'AppBundle\\Entity\\User\\Bookmark',
        ]);
    }
}
