<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HkLIyyCService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.HkLIyyC' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.HkLIyyC'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'connection' => ['privates', '.errored..service_locator.HkLIyyC.AppBundle\\Entity\\Connection', NULL, 'Cannot autowire service ".service_locator.HkLIyyC": it needs an instance of "AppBundle\\Entity\\Connection" but this type has been excluded in "config/services.yaml".'],
        ], [
            'connection' => 'AppBundle\\Entity\\Connection',
        ]);
    }
}
