<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QtIl7PService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.qtIl7_p' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.qtIl7_p'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'asset' => ['privates', '.errored..service_locator.qtIl7_p.AppBundle\\Entity\\Connection\\Mediacockpit\\Asset', NULL, 'Cannot autowire service ".service_locator.qtIl7_p": it needs an instance of "AppBundle\\Entity\\Connection\\Mediacockpit\\Asset" but this type has been excluded in "config/services.yaml".'],
        ], [
            'asset' => 'AppBundle\\Entity\\Connection\\Mediacockpit\\Asset',
        ]);
    }
}
