<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_UxPo0S6Service extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.uxPo0S6' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.uxPo0S6'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'font' => ['privates', '.errored..service_locator.uxPo0S6.AppBundle\\Entity\\Setting\\Font', NULL, 'Cannot autowire service ".service_locator.uxPo0S6": it needs an instance of "AppBundle\\Entity\\Setting\\Font" but this type has been excluded in "config/services.yaml".'],
        ], [
            'font' => 'AppBundle\\Entity\\Setting\\Font',
        ]);
    }
}
