<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_AjA0AJAService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.AjA0AJA' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.AjA0AJA'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'category' => ['privates', '.errored..service_locator.AjA0AJA.AppBundle\\Entity\\Category', NULL, 'Cannot autowire service ".service_locator.AjA0AJA": it needs an instance of "AppBundle\\Entity\\Category" but this type has been excluded in "config/services.yaml".'],
        ], [
            'category' => 'AppBundle\\Entity\\Category',
        ]);
    }
}
