<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_L9Qht7RService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.L9Qht7R' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.L9Qht7R'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'azure' => ['privates', 'hwi_oauth.resource_owner.azure', 'getHwiOauth_ResourceOwner_AzureService', true],
            'facebook' => ['privates', 'hwi_oauth.resource_owner.facebook', 'getHwiOauth_ResourceOwner_FacebookService', true],
            'oauth' => ['privates', 'hwi_oauth.resource_owner.oauth', 'getHwiOauth_ResourceOwner_OauthService', true],
            'okta' => ['privates', 'hwi_oauth.resource_owner.okta', 'getHwiOauth_ResourceOwner_OktaService', true],
        ], [
            'azure' => '?',
            'facebook' => '?',
            'oauth' => '?',
            'okta' => '?',
        ]);
    }
}
