<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PL_14LVService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.PL.14LV' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.PL.14LV'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'element' => ['privates', '.errored..service_locator.PL.14LV.AppBundle\\Entity\\Element', NULL, 'Cannot autowire service ".service_locator.PL.14LV": it needs an instance of "AppBundle\\Entity\\Element" but this type has been excluded in "config/services.yaml".'],
            'translator' => ['services', 'translator', 'getTranslatorService', false],
        ], [
            'element' => 'AppBundle\\Entity\\Element',
            'translator' => '?',
        ]);
    }
}
