<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MKpQ3NhService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.MKpQ3Nh' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.MKpQ3Nh'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'comment' => ['privates', '.errored..service_locator.MKpQ3Nh.AppBundle\\Entity\\Element\\ElementComment', NULL, 'Cannot autowire service ".service_locator.MKpQ3Nh": it needs an instance of "AppBundle\\Entity\\Element\\ElementComment" but this type has been excluded in "config/services.yaml".'],
            'element' => ['privates', '.errored..service_locator.MKpQ3Nh.AppBundle\\Entity\\Element', NULL, 'Cannot autowire service ".service_locator.MKpQ3Nh": it needs an instance of "AppBundle\\Entity\\Element" but this type has been excluded in "config/services.yaml".'],
        ], [
            'comment' => 'AppBundle\\Entity\\Element\\ElementComment',
            'element' => 'AppBundle\\Entity\\Element',
        ]);
    }
}
