<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_5QYkH_YService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.5QYkH.Y' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.5QYkH.Y'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'element' => ['privates', '.errored..service_locator.5QYkH.Y.AppBundle\\Entity\\Element', NULL, 'Cannot autowire service ".service_locator.5QYkH.Y": it needs an instance of "AppBundle\\Entity\\Element" but this type has been excluded in "config/services.yaml".'],
            'fileTransfer' => ['privates', '.errored..service_locator.5QYkH.Y.AppBundle\\Entity\\myHub\\FileTransfer', NULL, 'Cannot autowire service ".service_locator.5QYkH.Y": it needs an instance of "AppBundle\\Entity\\myHub\\FileTransfer" but this type has been excluded in "config/services.yaml".'],
        ], [
            'element' => 'AppBundle\\Entity\\Element',
            'fileTransfer' => 'AppBundle\\Entity\\myHub\\FileTransfer',
        ]);
    }
}
