<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HgFFgQuService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.HgFFgQu' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.HgFFgQu'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'element' => ['privates', '.errored..service_locator.HgFFgQu.AppBundle\\Entity\\Element', NULL, 'Cannot autowire service ".service_locator.HgFFgQu": it needs an instance of "AppBundle\\Entity\\Element" but this type has been excluded in "config/services.yaml".'],
            'media' => ['privates', '.errored..service_locator.HgFFgQu.AppBundle\\Entity\\SmartTool\\Framing\\FramingMedia', NULL, 'Cannot autowire service ".service_locator.HgFFgQu": it needs an instance of "AppBundle\\Entity\\SmartTool\\Framing\\FramingMedia" but this type has been excluded in "config/services.yaml".'],
        ], [
            'element' => 'AppBundle\\Entity\\Element',
            'media' => 'AppBundle\\Entity\\SmartTool\\Framing\\FramingMedia',
        ]);
    }
}
