<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Gmz2_Z3Service extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.Gmz2.Z3' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Gmz2.Z3'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'comment' => ['privates', '.errored..service_locator.Gmz2.Z3.AppBundle\\Entity\\SmartTool\\Inspiration\\InspirationComment', NULL, 'Cannot autowire service ".service_locator.Gmz2.Z3": it needs an instance of "AppBundle\\Entity\\SmartTool\\Inspiration\\InspirationComment" but this type has been excluded in "config/services.yaml".'],
            'element' => ['privates', '.errored..service_locator.Gmz2.Z3.AppBundle\\Entity\\Element', NULL, 'Cannot autowire service ".service_locator.Gmz2.Z3": it needs an instance of "AppBundle\\Entity\\Element" but this type has been excluded in "config/services.yaml".'],
        ], [
            'comment' => 'AppBundle\\Entity\\SmartTool\\Inspiration\\InspirationComment',
            'element' => 'AppBundle\\Entity\\Element',
        ]);
    }
}
