<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAttributeServiceService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'AppBundle\Services\Element\AttributeService' shared autowired service.
     *
     * @return \AppBundle\Services\Element\AttributeService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/wirdesign-communication-ag/wirhub/Services/Element/AttributeService.php';

        return $container->privates['AppBundle\\Services\\Element\\AttributeService'] = new \AppBundle\Services\Element\AttributeService(($container->privates['AppBundle\\Repository\\SmartBlock\\Attribute\\TureOrFalseRepository'] ?? $container->getTureOrFalseRepositoryService()), ($container->privates['AppBundle\\Repository\\SmartBlock\\Attribute\\ChoiceRepository'] ?? $container->getChoiceRepositoryService()), ($container->privates['AppBundle\\Repository\\SmartBlock\\Attribute\\ColorRepository'] ?? $container->getColorRepository2Service()), ($container->privates['AppBundle\\Repository\\SmartBlock\\Attribute\\UserRepository'] ?? $container->getUserRepository2Service()));
    }
}
