<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAjaxController2Service extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'AppBundle\Controller\Element\AjaxController' shared autowired service.
     *
     * @return \AppBundle\Controller\Element\AjaxController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/wirdesign-communication-ag/wirhub/Controller/Element/AjaxController.php';

        return $container->services['AppBundle\\Controller\\Element\\AjaxController'] = new \AppBundle\Controller\Element\AjaxController(\dirname(__DIR__, 6), ($container->services['event_dispatcher'] ?? $container->getEventDispatcherService()), ($container->privates['form.factory'] ?? $container->getForm_FactoryService()), ($container->privates['AppBundle\\Services\\ResponseService'] ?? $container->load('getResponseServiceService')), ($container->privates['AppBundle\\Services\\UserService'] ?? $container->getUserServiceService()));
    }
}
