<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApprovalController2Service extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'AppBundle\Controller\Settings\Category\ApprovalController' shared autowired service.
     *
     * @return \AppBundle\Controller\Settings\Category\ApprovalController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/wirdesign-communication-ag/wirhub/Controller/Settings/Category/ApprovalController.php';

        return $container->services['AppBundle\\Controller\\Settings\\Category\\ApprovalController'] = new \AppBundle\Controller\Settings\Category\ApprovalController(($container->privates['AppBundle\\Repository\\Category\\ApprovalRepository'] ?? $container->load('getApprovalRepositoryService')));
    }
}
