<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAccessTokenServiceService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'AppBundle\Services\User\AccessTokenService' shared autowired service.
     *
     * @return \AppBundle\Services\User\AccessTokenService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/wirdesign-communication-ag/wirhub/Services/User/AccessTokenService.php';

        return $container->privates['AppBundle\\Services\\User\\AccessTokenService'] = new \AppBundle\Services\User\AccessTokenService(($container->privates['AppBundle\\Repository\\User\\AccessTokenRepository'] ?? $container->load('getAccessTokenRepositoryService')));
    }
}
