<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAttributeFilterFormTypeService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'AppBundle\Form\Element\SmartBlock\Mediacockpit\AttributeFilterFormType' shared autowired service.
     *
     * @return \AppBundle\Form\Element\SmartBlock\Mediacockpit\AttributeFilterFormType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 6).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 6).'/vendor/wirdesign-communication-ag/wirhub/Form/Element/SmartBlock/Mediacockpit/AttributeFilterFormType.php';

        return $container->privates['AppBundle\\Form\\Element\\SmartBlock\\Mediacockpit\\AttributeFilterFormType'] = new \AppBundle\Form\Element\SmartBlock\Mediacockpit\AttributeFilterFormType(($container->privates['AppBundle\\Repository\\Connection\\Mediacockpit\\AttributeRepository'] ?? $container->getAttributeRepositoryService()));
    }
}
