<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAzureUserDataConnectorService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'AppBundle\Component\Security\AzureUserDataConnector' shared autowired service.
     *
     * @return \AppBundle\Component\Security\AzureUserDataConnector
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/wirdesign-communication-ag/wirhub/Component/Security/UserDataConnectorInterface.php';
        include_once \dirname(__DIR__, 6).'/vendor/wirdesign-communication-ag/wirhub/Component/Security/AzureUserDataConnector.php';

        return $container->privates['AppBundle\\Component\\Security\\AzureUserDataConnector'] = new \AppBundle\Component\Security\AzureUserDataConnector(($container->services['Symfony\\Contracts\\HttpClient\\HttpClientInterface'] ?? $container->getHttpClientInterfaceService()), $container->getEnv('string:APP_LOCALE'));
    }
}
