<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminTableServiceService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'AppBundle\Services\User\AdminTableService' shared autowired service.
     *
     * @return \AppBundle\Services\User\AdminTableService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/wirdesign-communication-ag/wirhub/Component/Interfaces/TableServiceInterface.php';
        include_once \dirname(__DIR__, 6).'/vendor/wirdesign-communication-ag/wirhub/Services/TableService.php';
        include_once \dirname(__DIR__, 6).'/vendor/wirdesign-communication-ag/wirhub/Services/User/AdminTableService.php';

        return $container->privates['AppBundle\\Services\\User\\AdminTableService'] = new \AppBundle\Services\User\AdminTableService(($container->privates['AppBundle\\Repository\\User\\GroupRepository'] ?? $container->getGroupRepositoryService()), ($container->privates['AppBundle\\Repository\\UserRepository'] ?? $container->getUserRepositoryService()));
    }
}
