<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAssetControllerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'AppBundle\Controller\Settings\Font\AssetController' shared autowired service.
     *
     * @return \AppBundle\Controller\Settings\Font\AssetController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/wirdesign-communication-ag/wirhub/Controller/Settings/Font/AssetController.php';

        return $container->services['AppBundle\\Controller\\Settings\\Font\\AssetController'] = new \AppBundle\Controller\Settings\Font\AssetController(\dirname(__DIR__, 6));
    }
}
