<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAttributeStandardValueRepositoryService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'AppBundle\Repository\Connection\Mediacockpit\AttributeStandardValueRepository' shared autowired service.
     *
     * @return \AppBundle\Repository\Connection\Mediacockpit\AttributeStandardValueRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/wirdesign-communication-ag/wirhub/Repository/Connection/Mediacockpit/AttributeStandardValueRepository.php';

        return $container->privates['AppBundle\\Repository\\Connection\\Mediacockpit\\AttributeStandardValueRepository'] = new \AppBundle\Repository\Connection\Mediacockpit\AttributeStandardValueRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
