<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApprovalMessageFormTypeService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'AppBundle\Form\Category\ApprovalMessageFormType' shared autowired service.
     *
     * @return \AppBundle\Form\Category\ApprovalMessageFormType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 6).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 6).'/vendor/wirdesign-communication-ag/wirhub/Form/Category/ApprovalMessageFormType.php';

        return $container->privates['AppBundle\\Form\\Category\\ApprovalMessageFormType'] = new \AppBundle\Form\Category\ApprovalMessageFormType();
    }
}
