<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAjaxControllerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'AppBundle\Controller\AjaxController' shared autowired service.
     *
     * @return \AppBundle\Controller\AjaxController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/wirdesign-communication-ag/wirhub/Controller/AjaxController.php';

        return $container->services['AppBundle\\Controller\\AjaxController'] = new \AppBundle\Controller\AjaxController(($container->privates['AppBundle\\Repository\\CategoryRepository'] ?? $container->getCategoryRepositoryService()), ($container->privates['AppBundle\\Repository\\ElementRepository'] ?? $container->getElementRepositoryService()), ($container->privates['AppBundle\\Repository\\Element\\ElementCommentRepository'] ?? $container->getElementCommentRepositoryService()), ($container->privates['AppBundle\\Repository\\SpaceRepository'] ?? $container->getSpaceRepositoryService()), ($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()), ($container->privates['form.factory'] ?? $container->getForm_FactoryService()), ($container->privates['AppBundle\\Router\\PersistentQueryRouter'] ?? $container->getPersistentQueryRouterService()), ($container->privates['AppBundle\\Services\\ShortLinkService'] ?? $container->load('getShortLinkServiceService')), ($container->privates['AppBundle\\Services\\SpaceService'] ?? $container->getSpaceServiceService()), ($container->privates['AppBundle\\Services\\UserService'] ?? $container->getUserServiceService()));
    }
}
