<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBookmarkControllerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'AppBundle\Controller\User\BookmarkController' shared autowired service.
     *
     * @return \AppBundle\Controller\User\BookmarkController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/wirdesign-communication-ag/wirhub/Controller/User/BookmarkController.php';

        return $container->services['AppBundle\\Controller\\User\\BookmarkController'] = new \AppBundle\Controller\User\BookmarkController(($container->privates['AppBundle\\Repository\\User\\BookmarkRepository'] ?? $container->getBookmarkRepositoryService()), ($container->privates['AppBundle\\Repository\\ElementRepository'] ?? $container->getElementRepositoryService()), ($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()), ($container->privates['AppBundle\\Services\\SnackbarService'] ?? $container->load('getSnackbarServiceService')), ($container->privates['AppBundle\\Services\\UserService'] ?? $container->getUserServiceService()));
    }
}
