<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBookmarkService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.NCpT9q5.AppBundle\Entity\User\Bookmark' shared service.
     *
     * @return \AppBundle\Entity\User\Bookmark
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.NCpT9q5": it needs an instance of "AppBundle\\Entity\\User\\Bookmark" but this type has been excluded in "config/services.yaml".');
    }
}
