<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCategoryController3Service extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'AppBundle\Controller\Settings\CategoryController' shared autowired service.
     *
     * @return \AppBundle\Controller\Settings\CategoryController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/wirdesign-communication-ag/wirhub/Controller/Settings/CategoryController.php';

        return $container->services['AppBundle\\Controller\\Settings\\CategoryController'] = new \AppBundle\Controller\Settings\CategoryController(($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()), ($container->services['event_dispatcher'] ?? $container->getEventDispatcherService()), ($container->privates['AppBundle\\Repository\\CategoryRepository'] ?? $container->getCategoryRepositoryService()), ($container->privates['AppBundle\\Repository\\ElementRepository'] ?? $container->getElementRepositoryService()), ($container->privates['AppBundle\\Services\\CategoryService'] ?? $container->getCategoryServiceService()), ($container->privates['AppBundle\\Services\\ResponseService'] ?? $container->load('getResponseServiceService')), ($container->privates['AppBundle\\Services\\SpaceService'] ?? $container->getSpaceServiceService()), ($container->privates['AppBundle\\Services\\UserService'] ?? $container->getUserServiceService()));
    }
}
