<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConfigService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.MtGeXB0.AppBundle\Entity\Config' shared service.
     *
     * @return \AppBundle\Entity\Config
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.MtGeXB0": it needs an instance of "AppBundle\\Entity\\Config" but this type has been excluded in "config/services.yaml".');
    }
}
