<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConnectionCommandService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'AppBundle\Command\Debug\ConnectionCommand' shared autowired service.
     *
     * @return \AppBundle\Command\Debug\ConnectionCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 6).'/vendor/wirdesign-communication-ag/wirhub/Command/Debug/ConnectionCommand.php';

        $container->privates['AppBundle\\Command\\Debug\\ConnectionCommand'] = $instance = new \AppBundle\Command\Debug\ConnectionCommand(($container->privates['AppBundle\\Services\\Feature\\Connection\\MediacockpitService'] ?? $container->getMediacockpitServiceService()));

        $instance->setName('app:debug:connection');

        return $instance;
    }
}
