<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getChapterTeaserItemService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.M9u3xj3.AppBundle\Entity\SmartBlock\ChapterTeaserItem' shared service.
     *
     * @return \AppBundle\Entity\SmartBlock\ChapterTeaserItem
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.M9u3xj3": it needs an instance of "AppBundle\\Entity\\SmartBlock\\ChapterTeaserItem" but this type has been excluded in "config/services.yaml".');
    }
}
