<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getChunkedUploadTypeService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'AppBundle\Form\File\ChunkedUploadType' shared autowired service.
     *
     * @return \AppBundle\Form\File\ChunkedUploadType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 6).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 6).'/vendor/wirdesign-communication-ag/wirhub/Form/File/ChunkedUploadType.php';

        return $container->privates['AppBundle\\Form\\File\\ChunkedUploadType'] = new \AppBundle\Form\File\ChunkedUploadType(($container->services['translator'] ?? $container->getTranslatorService()));
    }
}
