<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getColorControllerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'AppBundle\Controller\Settings\ColorController' shared autowired service.
     *
     * @return \AppBundle\Controller\Settings\ColorController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/wirdesign-communication-ag/wirhub/Controller/Settings/ColorController.php';

        return $container->services['AppBundle\\Controller\\Settings\\ColorController'] = new \AppBundle\Controller\Settings\ColorController(($container->privates['form.factory'] ?? $container->getForm_FactoryService()), ($container->privates['AppBundle\\Repository\\Setting\\ColorRepository'] ?? $container->getColorRepositoryService()), ($container->privates['AppBundle\\Services\\Vendor\\DoctrineService'] ?? $container->load('getDoctrineServiceService')), ($container->privates['AppBundle\\Services\\ResponseService'] ?? $container->load('getResponseServiceService')));
    }
}
