<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getChainUserDataConnectorService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'AppBundle\Component\Security\ChainUserDataConnector' shared autowired service.
     *
     * @return \AppBundle\Component\Security\ChainUserDataConnector
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/wirdesign-communication-ag/wirhub/Component/Security/UserDataConnectorInterface.php';
        include_once \dirname(__DIR__, 6).'/vendor/wirdesign-communication-ag/wirhub/Component/Security/ChainUserDataConnector.php';
        include_once \dirname(__DIR__, 6).'/vendor/wirdesign-communication-ag/wirhub/Component/Security/OAuthUserDataConnector.php';
        include_once \dirname(__DIR__, 6).'/vendor/wirdesign-communication-ag/wirhub/Component/Security/OktaUserDataConnector.php';

        return $container->privates['AppBundle\\Component\\Security\\ChainUserDataConnector'] = new \AppBundle\Component\Security\ChainUserDataConnector([0 => ($container->privates['AppBundle\\Component\\Security\\AzureUserDataConnector'] ?? $container->load('getAzureUserDataConnectorService')), 1 => ($container->privates['AppBundle\\Component\\Security\\OAuthUserDataConnector'] ??= new \AppBundle\Component\Security\OAuthUserDataConnector()), 2 => ($container->privates['AppBundle\\Component\\Security\\OktaUserDataConnector'] ??= new \AppBundle\Component\Security\OktaUserDataConnector())]);
    }
}
