<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCategory3Service extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.SYzIEmF.AppBundle\Entity\Category' shared service.
     *
     * @return \AppBundle\Entity\Category
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.SYzIEmF": it needs an instance of "AppBundle\\Entity\\Category" but this type has been excluded in "config/services.yaml".');
    }
}
