<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getColorFormTypeService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'AppBundle\Form\Setting\ColorFormType' shared autowired service.
     *
     * @return \AppBundle\Form\Setting\ColorFormType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 6).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 6).'/vendor/wirdesign-communication-ag/wirhub/Form/Setting/ColorFormType.php';

        $a = ($container->privates['AppBundle\\Services\\SpaceService'] ?? $container->getSpaceServiceService());

        if (isset($container->privates['AppBundle\\Form\\Setting\\ColorFormType'])) {
            return $container->privates['AppBundle\\Form\\Setting\\ColorFormType'];
        }

        return $container->privates['AppBundle\\Form\\Setting\\ColorFormType'] = new \AppBundle\Form\Setting\ColorFormType(($container->privates['AppBundle\\Repository\\ConfigRepository'] ?? $container->getConfigRepositoryService()), $a);
    }
}
