<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCollectionController2Service extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'AppBundle\Controller\Feature\DownloadCenter\CollectionController' shared autowired service.
     *
     * @return \AppBundle\Controller\Feature\DownloadCenter\CollectionController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/wirdesign-communication-ag/wirhub/Controller/Feature/DownloadCenter/CollectionController.php';

        return $container->services['AppBundle\\Controller\\Feature\\DownloadCenter\\CollectionController'] = new \AppBundle\Controller\Feature\DownloadCenter\CollectionController(\dirname(__DIR__, 6), ($container->privates['AppBundle\\Repository\\FileRepository'] ?? $container->getFileRepositoryService()), ($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()), ($container->privates['AppBundle\\Services\\File\\PathService'] ?? $container->getPathServiceService()));
    }
}
