<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConnectionControllerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'AppBundle\Controller\Feature\ConnectionController' shared autowired service.
     *
     * @return \AppBundle\Controller\Feature\ConnectionController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/wirdesign-communication-ag/wirhub/Controller/Feature/ConnectionController.php';

        return $container->services['AppBundle\\Controller\\Feature\\ConnectionController'] = new \AppBundle\Controller\Feature\ConnectionController(($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()), ($container->privates['twig'] ?? $container->getTwigService()), ($container->privates['form.factory'] ?? $container->getForm_FactoryService()), ($container->privates['AppBundle\\Services\\Feature\\Connection\\MediacockpitService'] ?? $container->getMediacockpitServiceService()), ($container->services['translator'] ?? $container->getTranslatorService()));
    }
}
