<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCategoryDailyRepositoryService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'AppBundle\Repository\Metrics\CategoryDailyRepository' shared autowired service.
     *
     * @return \AppBundle\Repository\Metrics\CategoryDailyRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/wirdesign-communication-ag/wirhub/Repository/Metrics/CategoryDailyRepository.php';

        return $container->privates['AppBundle\\Repository\\Metrics\\CategoryDailyRepository'] = new \AppBundle\Repository\Metrics\CategoryDailyRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
