<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCronjobControllerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'AppBundle\Controller\Admin\System\CronjobController' shared autowired service.
     *
     * @return \AppBundle\Controller\Admin\System\CronjobController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/wirdesign-communication-ag/wirhub/Controller/Admin/System/CronjobController.php';

        return $container->services['AppBundle\\Controller\\Admin\\System\\CronjobController'] = new \AppBundle\Controller\Admin\System\CronjobController();
    }
}
