<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCraue_Form_Flow_StorageService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'craue.form.flow.storage' shared service.
     *
     * @return \Craue\FormFlowBundle\Storage\SessionStorage
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/craue/formflow-bundle/Storage/StorageInterface.php';
        include_once \dirname(__DIR__, 6).'/vendor/craue/formflow-bundle/Storage/SessionProviderTrait.php';
        include_once \dirname(__DIR__, 6).'/vendor/craue/formflow-bundle/Storage/SessionStorage.php';

        return $container->services['craue.form.flow.storage'] = new \Craue\FormFlowBundle\Storage\SessionStorage(($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()));
    }
}
