<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCraue_Form_Flow_FormExtensionService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'craue.form.flow.form_extension' shared service.
     *
     * @return \Craue\FormFlowBundle\Form\Extension\FormFlowFormExtension
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/symfony/form/FormTypeExtensionInterface.php';
        include_once \dirname(__DIR__, 6).'/vendor/symfony/form/AbstractTypeExtension.php';
        include_once \dirname(__DIR__, 6).'/vendor/craue/formflow-bundle/Form/Extension/FormFlowFormExtension.php';

        return $container->privates['craue.form.flow.form_extension'] = new \Craue\FormFlowBundle\Form\Extension\FormFlowFormExtension();
    }
}
