<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContactControllerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'AppBundle\Controller\Element\SmartBlock\ContactController' shared autowired service.
     *
     * @return \AppBundle\Controller\Element\SmartBlock\ContactController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/wirdesign-communication-ag/wirhub/Controller/Element/SmartBlock/ContactController.php';

        return $container->services['AppBundle\\Controller\\Element\\SmartBlock\\ContactController'] = new \AppBundle\Controller\Element\SmartBlock\ContactController(($container->privates['form.factory'] ?? $container->getForm_FactoryService()), ($container->privates['AppBundle\\Services\\LogService'] ?? $container->load('getLogServiceService')), ($container->privates['mailer.mailer'] ?? $container->load('getMailer_MailerService')), ($container->privates['AppBundle\\Services\\ResponseService'] ?? $container->load('getResponseServiceService')), ($container->services['translator'] ?? $container->getTranslatorService()), ($container->privates['AppBundle\\Services\\UserService'] ?? $container->getUserServiceService()), ($container->privates['AppBundle\\Repository\\ConfigRepository'] ?? $container->getConfigRepositoryService()));
    }
}
