<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCraue_Form_Flow_EventListener_PreviousStepInvalidService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'craue.form.flow.event_listener.previous_step_invalid' shared service.
     *
     * @return \Craue\FormFlowBundle\EventListener\PreviousStepInvalidEventListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/craue/formflow-bundle/EventListener/EventListenerWithTranslatorTrait.php';
        include_once \dirname(__DIR__, 6).'/vendor/craue/formflow-bundle/EventListener/PreviousStepInvalidEventListener.php';

        $container->privates['craue.form.flow.event_listener.previous_step_invalid'] = $instance = new \Craue\FormFlowBundle\EventListener\PreviousStepInvalidEventListener();

        $instance->setTranslator(($container->services['translator'] ?? $container->getTranslatorService()));

        return $instance;
    }
}
