<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDownloadControllerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'AppBundle\Controller\DownloadController' shared autowired service.
     *
     * @return \AppBundle\Controller\DownloadController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/wirdesign-communication-ag/wirhub/Controller/DownloadController.php';

        return $container->services['AppBundle\\Controller\\DownloadController'] = new \AppBundle\Controller\DownloadController(\dirname(__DIR__, 6), ($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()), ($container->privates['twig'] ?? $container->getTwigService()), ($container->privates['AppBundle\\Services\\myHub\\FileTransferService'] ?? $container->load('getFileTransferServiceService')), ($container->privates['AppBundle\\Router\\PersistentQueryRouter'] ?? $container->getPersistentQueryRouterService()));
    }
}
