<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDefaultController5Service extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'AppBundle\Controller\Settings\Analytics\DefaultController' shared autowired service.
     *
     * @return \AppBundle\Controller\Settings\Analytics\DefaultController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/wirdesign-communication-ag/wirhub/Controller/Settings/Analytics/DefaultController.php';

        return $container->services['AppBundle\\Controller\\Settings\\Analytics\\DefaultController'] = new \AppBundle\Controller\Settings\Analytics\DefaultController(($container->privates['AppBundle\\Repository\\Metrics\\CategoryDailyRepository'] ?? $container->load('getCategoryDailyRepositoryService')), ($container->privates['form.factory'] ?? $container->getForm_FactoryService()));
    }
}
