<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDefaultControllerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'AppBundle\Controller\Admin\DefaultController' shared autowired service.
     *
     * @return \AppBundle\Controller\Admin\DefaultController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/wirdesign-communication-ag/wirhub/Controller/Admin/DefaultController.php';

        return $container->services['AppBundle\\Controller\\Admin\\DefaultController'] = new \AppBundle\Controller\Admin\DefaultController(($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()), ($container->privates['AppBundle\\Repository\\ConfigRepository'] ?? $container->getConfigRepositoryService()), ($container->services['event_dispatcher'] ?? $container->getEventDispatcherService()));
    }
}
