<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDoctrineServiceService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'AppBundle\Services\Vendor\DoctrineService' shared autowired service.
     *
     * @return \AppBundle\Services\Vendor\DoctrineService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/wirdesign-communication-ag/wirhub/Services/Vendor/DoctrineService.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService());

        if (isset($container->privates['AppBundle\\Services\\Vendor\\DoctrineService'])) {
            return $container->privates['AppBundle\\Services\\Vendor\\DoctrineService'];
        }

        return $container->privates['AppBundle\\Services\\Vendor\\DoctrineService'] = new \AppBundle\Services\Vendor\DoctrineService($a);
    }
}
