<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDoctrine_Migrations_ConfigurationService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'doctrine.migrations.configuration' shared service.
     *
     * @return \Doctrine\Migrations\Configuration\Configuration
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/doctrine/migrations/lib/Doctrine/Migrations/Configuration/Configuration.php';

        $container->privates['doctrine.migrations.configuration'] = $instance = new \Doctrine\Migrations\Configuration\Configuration();

        $instance->addMigrationsDirectory('DoctrineMigrations', (\dirname(__DIR__, 6).'/migrations'));
        $instance->addMigrationsDirectory('Application\\Migrations', (\dirname(__DIR__, 6).'/vendor/wirdesign-communication-ag/wirhub/Migrations'));
        $instance->setMigrationOrganization('year');
        $instance->setAllOrNothing(false);
        $instance->setCheckDatabasePlatform(true);
        $instance->setTransactional(true);
        $instance->setMetadataStorageConfiguration(($container->privates['doctrine.migrations.storage.table_storage'] ?? $container->load('getDoctrine_Migrations_Storage_TableStorageService')));

        return $instance;
    }
}
