<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDoDontService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.73E6mJl.AppBundle\Entity\SmartBlock\DoDont' shared service.
     *
     * @return \AppBundle\Entity\SmartBlock\DoDont
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.73E6mJl": it needs an instance of "AppBundle\\Entity\\SmartBlock\\DoDont" but this type has been excluded in "config/services.yaml".');
    }
}
