<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDefaultController2Service extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'AppBundle\Controller\Admin\User\DefaultController' shared autowired service.
     *
     * @return \AppBundle\Controller\Admin\User\DefaultController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/wirdesign-communication-ag/wirhub/Controller/Admin/User/DefaultController.php';

        return $container->services['AppBundle\\Controller\\Admin\\User\\DefaultController'] = new \AppBundle\Controller\Admin\User\DefaultController(($container->services['knp_paginator'] ?? $container->load('getKnpPaginatorService')), ($container->privates['AppBundle\\Services\\User\\AdminTableService'] ?? $container->load('getAdminTableServiceService')), ($container->privates['AppBundle\\Repository\\User\\GroupRepository'] ?? $container->getGroupRepositoryService()));
    }
}
