<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDoctrine_Fixtures_LoaderService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'doctrine.fixtures.loader' shared service.
     *
     * @return \Doctrine\Bundle\FixturesBundle\Loader\SymfonyFixturesLoader
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/doctrine/data-fixtures/src/Loader.php';
        include_once \dirname(__DIR__, 6).'/vendor/symfony/doctrine-bridge/DataFixtures/ContainerAwareLoader.php';
        include_once \dirname(__DIR__, 6).'/vendor/doctrine/doctrine-fixtures-bundle/Loader/SymfonyFixturesLoader.php';
        include_once \dirname(__DIR__, 6).'/vendor/doctrine/data-fixtures/src/FixtureInterface.php';
        include_once \dirname(__DIR__, 6).'/vendor/doctrine/data-fixtures/src/SharedFixtureInterface.php';
        include_once \dirname(__DIR__, 6).'/vendor/doctrine/data-fixtures/src/AbstractFixture.php';
        include_once \dirname(__DIR__, 6).'/vendor/doctrine/doctrine-fixtures-bundle/ORMFixtureInterface.php';
        include_once \dirname(__DIR__, 6).'/vendor/doctrine/doctrine-fixtures-bundle/Fixture.php';
        include_once \dirname(__DIR__, 6).'/vendor/doctrine/data-fixtures/src/DependentFixtureInterface.php';
        include_once \dirname(__DIR__, 6).'/vendor/wirdesign-communication-ag/wirhub/DataFixtures/CategoryDashboardWithSpacesFixture.php';
        include_once \dirname(__DIR__, 6).'/vendor/wirdesign-communication-ag/wirhub/DataFixtures/ConfigFixture.php';
        include_once \dirname(__DIR__, 6).'/vendor/wirdesign-communication-ag/wirhub/DataFixtures/DefaultSpaceFixture.php';
        include_once \dirname(__DIR__, 6).'/vendor/wirdesign-communication-ag/wirhub/DataFixtures/HeadlinesFixture.php';
        include_once \dirname(__DIR__, 6).'/vendor/wirdesign-communication-ag/wirhub/DataFixtures/MultipleSpacesFixture.php';
        include_once \dirname(__DIR__, 6).'/vendor/wirdesign-communication-ag/wirhub/DataFixtures/PageFixtures.php';
        include_once \dirname(__DIR__, 6).'/vendor/wirdesign-communication-ag/wirhub/DataFixtures/Setting/TemplateFixture.php';

        $container->privates['doctrine.fixtures.loader'] = $instance = new \Doctrine\Bundle\FixturesBundle\Loader\SymfonyFixturesLoader($container);

        $instance->addFixtures([0 => ['fixture' => ($container->privates['AppBundle\\DataFixtures\\AdminUser2Fixture'] ?? $container->load('getAdminUser2FixtureService')), 'groups' => []], 1 => ['fixture' => ($container->privates['AppBundle\\DataFixtures\\AdminUserFixture'] ?? $container->load('getAdminUserFixtureService')), 'groups' => []], 2 => ['fixture' => ($container->privates['AppBundle\\DataFixtures\\AppFixtures'] ?? $container->load('getAppFixturesService')), 'groups' => []], 3 => ['fixture' => ($container->privates['AppBundle\\DataFixtures\\CategoryDashboardWithSpacesFixture'] ??= new \AppBundle\DataFixtures\CategoryDashboardWithSpacesFixture()), 'groups' => []], 4 => ['fixture' => ($container->privates['AppBundle\\DataFixtures\\ConfigFixture'] ??= new \AppBundle\DataFixtures\ConfigFixture()), 'groups' => []], 5 => ['fixture' => ($container->privates['AppBundle\\DataFixtures\\DefaultSpaceFixture'] ??= new \AppBundle\DataFixtures\DefaultSpaceFixture()), 'groups' => []], 6 => ['fixture' => ($container->privates['AppBundle\\DataFixtures\\EditorUserFixture'] ?? $container->load('getEditorUserFixtureService')), 'groups' => []], 7 => ['fixture' => ($container->privates['AppBundle\\DataFixtures\\HeadlinesFixture'] ??= new \AppBundle\DataFixtures\HeadlinesFixture()), 'groups' => []], 8 => ['fixture' => ($container->privates['AppBundle\\DataFixtures\\MultipleSpacesFixture'] ??= new \AppBundle\DataFixtures\MultipleSpacesFixture()), 'groups' => []], 9 => ['fixture' => ($container->privates['AppBundle\\DataFixtures\\PageFixtures'] ??= new \AppBundle\DataFixtures\PageFixtures()), 'groups' => []], 10 => ['fixture' => ($container->privates['AppBundle\\DataFixtures\\Setting\\TemplateFixture'] ??= new \AppBundle\DataFixtures\Setting\TemplateFixture()), 'groups' => []], 11 => ['fixture' => ($container->privates['AppBundle\\DataFixtures\\StandardUserFixture'] ?? $container->load('getStandardUserFixtureService')), 'groups' => []]]);

        return $instance;
    }
}
