<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getElementUploadEventSubscriberService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'AppBundle\EventSubscriber\ElementUploadEventSubscriber' shared autowired service.
     *
     * @return \AppBundle\EventSubscriber\ElementUploadEventSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/wirdesign-communication-ag/wirhub/EventSubscriber/ElementUploadEventSubscriber.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService());

        if (isset($container->privates['AppBundle\\EventSubscriber\\ElementUploadEventSubscriber'])) {
            return $container->privates['AppBundle\\EventSubscriber\\ElementUploadEventSubscriber'];
        }
        $b = ($container->privates['AppBundle\\Services\\FileService'] ?? $container->getFileServiceService());

        if (isset($container->privates['AppBundle\\EventSubscriber\\ElementUploadEventSubscriber'])) {
            return $container->privates['AppBundle\\EventSubscriber\\ElementUploadEventSubscriber'];
        }

        return $container->privates['AppBundle\\EventSubscriber\\ElementUploadEventSubscriber'] = new \AppBundle\EventSubscriber\ElementUploadEventSubscriber($a, ($container->privates['AppBundle\\Repository\\Element\\ElementFileRepository'] ?? $container->getElementFileRepositoryService()), $b);
    }
}
