<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getElementFileEventSubscriberService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'AppBundle\EventSubscriber\ElementFileEventSubscriber' shared autowired service.
     *
     * @return \AppBundle\EventSubscriber\ElementFileEventSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/wirdesign-communication-ag/wirhub/EventSubscriber/ElementFileEventSubscriber.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService());

        if (isset($container->privates['AppBundle\\EventSubscriber\\ElementFileEventSubscriber'])) {
            return $container->privates['AppBundle\\EventSubscriber\\ElementFileEventSubscriber'];
        }

        return $container->privates['AppBundle\\EventSubscriber\\ElementFileEventSubscriber'] = new \AppBundle\EventSubscriber\ElementFileEventSubscriber(($container->privates['AppBundle\\Repository\\Element\\ElementFileRepository'] ?? $container->getElementFileRepositoryService()), $a);
    }
}
