<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getElementFileServiceService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'AppBundle\Services\Element\ElementFileService' shared autowired service.
     *
     * @return \AppBundle\Services\Element\ElementFileService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/wirdesign-communication-ag/wirhub/Services/Element/ElementFileService.php';

        return $container->privates['AppBundle\\Services\\Element\\ElementFileService'] = new \AppBundle\Services\Element\ElementFileService(($container->privates['AppBundle\\Repository\\Element\\ElementFileRepository'] ?? $container->getElementFileRepositoryService()));
    }
}
