<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEyeCatcherControllerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'AppBundle\Controller\Settings\SmartTool\Inspiration\EyeCatcherController' shared autowired service.
     *
     * @return \AppBundle\Controller\Settings\SmartTool\Inspiration\EyeCatcherController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/wirdesign-communication-ag/wirhub/Controller/Settings/SmartTool/Inspiration/EyeCatcherController.php';

        return $container->services['AppBundle\\Controller\\Settings\\SmartTool\\Inspiration\\EyeCatcherController'] = new \AppBundle\Controller\Settings\SmartTool\Inspiration\EyeCatcherController(($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()), ($container->privates['form.factory'] ?? $container->getForm_FactoryService()), ($container->privates['AppBundle\\Services\\FileService'] ?? $container->getFileServiceService()), ($container->privates['AppBundle\\Services\\Element\\SmartBlock\\InspirationService'] ?? $container->load('getInspirationServiceService')), ($container->privates['AppBundle\\Services\\ResponseService'] ?? $container->load('getResponseServiceService')), ($container->privates['AppBundle\\Services\\UserService'] ?? $container->getUserServiceService()));
    }
}
