<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getElementAliasEventSubscriberService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'AppBundle\EventSubscriber\ElementAliasEventSubscriber' shared autowired service.
     *
     * @return \AppBundle\EventSubscriber\ElementAliasEventSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/wirdesign-communication-ag/wirhub/EventSubscriber/ElementAliasEventSubscriber.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService());

        if (isset($container->privates['AppBundle\\EventSubscriber\\ElementAliasEventSubscriber'])) {
            return $container->privates['AppBundle\\EventSubscriber\\ElementAliasEventSubscriber'];
        }

        return $container->privates['AppBundle\\EventSubscriber\\ElementAliasEventSubscriber'] = new \AppBundle\EventSubscriber\ElementAliasEventSubscriber($a);
    }
}
