<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getElementAttributesEventSubscriberService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'AppBundle\EventSubscriber\ElementAttributesEventSubscriber' shared autowired service.
     *
     * @return \AppBundle\EventSubscriber\ElementAttributesEventSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/wirdesign-communication-ag/wirhub/EventSubscriber/ElementAttributesEventSubscriber.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService());

        if (isset($container->privates['AppBundle\\EventSubscriber\\ElementAttributesEventSubscriber'])) {
            return $container->privates['AppBundle\\EventSubscriber\\ElementAttributesEventSubscriber'];
        }

        return $container->privates['AppBundle\\EventSubscriber\\ElementAttributesEventSubscriber'] = new \AppBundle\EventSubscriber\ElementAttributesEventSubscriber($a, ($container->privates['AppBundle\\Services\\Element\\AttributeService'] ?? $container->load('getAttributeServiceService')));
    }
}
