<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEyeCatcherService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.2_q4aKD.AppBundle\Entity\SmartTool\Inspiration\EyeCatcher' shared service.
     *
     * @return \AppBundle\Entity\SmartTool\Inspiration\EyeCatcher
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.2_q4aKD": it needs an instance of "AppBundle\\Entity\\SmartTool\\Inspiration\\EyeCatcher" but this type has been excluded in "config/services.yaml".');
    }
}
