<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getElement14Service extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.PL.14LV.AppBundle\Entity\Element' shared service.
     *
     * @return \AppBundle\Entity\Element
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.PL.14LV": it needs an instance of "AppBundle\\Entity\\Element" but this type has been excluded in "config/services.yaml".');
    }
}
