<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFilterFormTypeService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'AppBundle\Form\Setting\Analytics\FilterFormType' shared autowired service.
     *
     * @return \AppBundle\Form\Setting\Analytics\FilterFormType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 6).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 6).'/vendor/wirdesign-communication-ag/wirhub/Form/Setting/Analytics/FilterFormType.php';

        return $container->privates['AppBundle\\Form\\Setting\\Analytics\\FilterFormType'] = new \AppBundle\Form\Setting\Analytics\FilterFormType();
    }
}
