<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFontService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.uxPo0S6.AppBundle\Entity\Setting\Font' shared service.
     *
     * @return \AppBundle\Entity\Setting\Font
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.uxPo0S6": it needs an instance of "AppBundle\\Entity\\Setting\\Font" but this type has been excluded in "config/services.yaml".');
    }
}
