<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFileTransferService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.5QYkH.Y.AppBundle\Entity\myHub\FileTransfer' shared service.
     *
     * @return \AppBundle\Entity\myHub\FileTransfer
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.5QYkH.Y": it needs an instance of "AppBundle\\Entity\\myHub\\FileTransfer" but this type has been excluded in "config/services.yaml".');
    }
}
