<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFileCleanUpCronjobSubscriberService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'AppBundle\EventSubscriber\Cronjob\FileCleanUpCronjobSubscriber' shared autowired service.
     *
     * @return \AppBundle\EventSubscriber\Cronjob\FileCleanUpCronjobSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/wirdesign-communication-ag/wirhub/Component/Interfaces/IsCronjobEventSubscriberInterface.php';
        include_once \dirname(__DIR__, 6).'/vendor/wirdesign-communication-ag/wirhub/EventSubscriber/Cronjob/FileCleanUpCronjobSubscriber.php';

        $a = ($container->privates['AppBundle\\Repository\\FileRepository'] ?? $container->getFileRepositoryService());

        if (isset($container->privates['AppBundle\\EventSubscriber\\Cronjob\\FileCleanUpCronjobSubscriber'])) {
            return $container->privates['AppBundle\\EventSubscriber\\Cronjob\\FileCleanUpCronjobSubscriber'];
        }
        $b = ($container->privates['AppBundle\\Services\\System\\CronjobService'] ?? $container->getCronjobServiceService());

        if (isset($container->privates['AppBundle\\EventSubscriber\\Cronjob\\FileCleanUpCronjobSubscriber'])) {
            return $container->privates['AppBundle\\EventSubscriber\\Cronjob\\FileCleanUpCronjobSubscriber'];
        }
        $c = ($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService());

        if (isset($container->privates['AppBundle\\EventSubscriber\\Cronjob\\FileCleanUpCronjobSubscriber'])) {
            return $container->privates['AppBundle\\EventSubscriber\\Cronjob\\FileCleanUpCronjobSubscriber'];
        }

        return $container->privates['AppBundle\\EventSubscriber\\Cronjob\\FileCleanUpCronjobSubscriber'] = new \AppBundle\EventSubscriber\Cronjob\FileCleanUpCronjobSubscriber(\dirname(__DIR__, 6), $a, ($container->privates['AppBundle\\Repository\\myHub\\FileTransferFileRepository'] ?? $container->load('getFileTransferFileRepositoryService')), $b, $c);
    }
}
