<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFramingDownloadServiceService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'AppBundle\Services\Element\SmartBlock\FramingDownloadService' shared autowired service.
     *
     * @return \AppBundle\Services\Element\SmartBlock\FramingDownloadService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/wirdesign-communication-ag/wirhub/Services/Element/SmartBlock/FramingDownloadService.php';

        return $container->privates['AppBundle\\Services\\Element\\SmartBlock\\FramingDownloadService'] = new \AppBundle\Services\Element\SmartBlock\FramingDownloadService(\dirname(__DIR__, 6), ($container->privates['AppBundle\\Repository\\SmartTool\\Framing\\FramingMediaRepository'] ?? $container->getFramingMediaRepositoryService()));
    }
}
