<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFile2Service extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.UamHolm.AppBundle\Entity\File' shared service.
     *
     * @return \AppBundle\Entity\File
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.UamHolm": it needs an instance of "AppBundle\\Entity\\File" but this type has been excluded in "config/services.yaml".');
    }
}
