<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFileTransferFileService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.zweMN_o.AppBundle\Entity\myHub\FileTransferFile' shared service.
     *
     * @return \AppBundle\Entity\myHub\FileTransferFile
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.zweMN_o": it needs an instance of "AppBundle\\Entity\\myHub\\FileTransferFile" but this type has been excluded in "config/services.yaml".');
    }
}
