<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFilesCommandService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'AppBundle\Command\Debug\FilesCommand' shared autowired service.
     *
     * @return \AppBundle\Command\Debug\FilesCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 6).'/vendor/wirdesign-communication-ag/wirhub/Command/Debug/FilesCommand.php';

        $container->privates['AppBundle\\Command\\Debug\\FilesCommand'] = $instance = new \AppBundle\Command\Debug\FilesCommand(\dirname(__DIR__, 6), ($container->privates['AppBundle\\Repository\\ElementRepository'] ?? $container->getElementRepositoryService()), ($container->privates['AppBundle\\Repository\\FileRepository'] ?? $container->getFileRepositoryService()), ($container->privates['AppBundle\\Repository\\Setting\\ThemeRepository'] ?? $container->getThemeRepositoryService()), ($container->privates['AppBundle\\Repository\\SmartBlock\\IconList\\IconRepository'] ?? $container->getIconRepositoryService()), ($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()));

        $instance->setName('app:debug:files');

        return $instance;
    }
}
