<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFrontendControllerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'AppBundle\Controller\Element\SmartBlock\MediaCockpit\FrontendController' shared autowired service.
     *
     * @return \AppBundle\Controller\Element\SmartBlock\MediaCockpit\FrontendController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/wirdesign-communication-ag/wirhub/Controller/Element/SmartBlock/MediaCockpit/FrontendController.php';

        return $container->services['AppBundle\\Controller\\Element\\SmartBlock\\MediaCockpit\\FrontendController'] = new \AppBundle\Controller\Element\SmartBlock\MediaCockpit\FrontendController(($container->privates['AppBundle\\Repository\\Connection\\Mediacockpit\\AssetRepository'] ?? $container->getAssetRepositoryService()), ($container->privates['AppBundle\\Repository\\Connection\\Mediacockpit\\AttributeRepository'] ?? $container->getAttributeRepositoryService()), ($container->privates['AppBundle\\Repository\\SmartBlock\\Attribute\\ChoiceRepository'] ?? $container->getChoiceRepositoryService()), ($container->privates['AppBundle\\Services\\Feature\\Connection\\MediacockpitService'] ?? $container->getMediacockpitServiceService()), ($container->privates['AppBundle\\Services\\UserService'] ?? $container->getUserServiceService()));
    }
}
