<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGroupService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.jbmhx.L.AppBundle\Entity\User\Group' shared service.
     *
     * @return \AppBundle\Entity\User\Group
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.jbmhx.L": it needs an instance of "AppBundle\\Entity\\User\\Group" but this type has been excluded in "config/services.yaml".');
    }
}
