<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGroupFormTypeService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'AppBundle\Form\Setting\SmartTool\Framing\GroupFormType' shared autowired service.
     *
     * @return \AppBundle\Form\Setting\SmartTool\Framing\GroupFormType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 6).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 6).'/vendor/wirdesign-communication-ag/wirhub/Form/Setting/SmartTool/Framing/GroupFormType.php';

        return $container->privates['AppBundle\\Form\\Setting\\SmartTool\\Framing\\GroupFormType'] = new \AppBundle\Form\Setting\SmartTool\Framing\GroupFormType();
    }
}
