<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGraphTransportFactoryService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'PMDevelopment\Mailer\Bridge\Microsoft\Transport\GraphTransportFactory' shared autowired service.
     *
     * @return \PMDevelopment\Mailer\Bridge\Microsoft\Transport\GraphTransportFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/symfony/mailer/Transport/TransportFactoryInterface.php';
        include_once \dirname(__DIR__, 6).'/vendor/symfony/mailer/Transport/AbstractTransportFactory.php';
        include_once \dirname(__DIR__, 6).'/vendor/pmdevelopment/microsoft-symfony-mailer/Transport/GraphTransportFactory.php';

        $a = ($container->services['event_dispatcher'] ?? $container->getEventDispatcherService());

        if (isset($container->privates['PMDevelopment\\Mailer\\Bridge\\Microsoft\\Transport\\GraphTransportFactory'])) {
            return $container->privates['PMDevelopment\\Mailer\\Bridge\\Microsoft\\Transport\\GraphTransportFactory'];
        }

        return $container->privates['PMDevelopment\\Mailer\\Bridge\\Microsoft\\Transport\\GraphTransportFactory'] = new \PMDevelopment\Mailer\Bridge\Microsoft\Transport\GraphTransportFactory($a, ($container->privates['monolog.logger'] ?? $container->getMonolog_LoggerService()));
    }
}
