<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGlobalContactFormTypeService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'AppBundle\Form\Setting\GlobalContactFormType' shared autowired service.
     *
     * @return \AppBundle\Form\Setting\GlobalContactFormType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 6).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 6).'/vendor/wirdesign-communication-ag/wirhub/Form/Setting/GlobalContactFormType.php';

        return $container->privates['AppBundle\\Form\\Setting\\GlobalContactFormType'] = new \AppBundle\Form\Setting\GlobalContactFormType(($container->privates['AppBundle\\Repository\\ConfigRepository'] ?? $container->getConfigRepositoryService()));
    }
}
