<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGroupServiceService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'AppBundle\Services\User\GroupService' shared autowired service.
     *
     * @return \AppBundle\Services\User\GroupService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/wirdesign-communication-ag/wirhub/Services/User/GroupService.php';

        return $container->privates['AppBundle\\Services\\User\\GroupService'] = new \AppBundle\Services\User\GroupService(($container->privates['AppBundle\\Repository\\CategoryRepository'] ?? $container->getCategoryRepositoryService()), ($container->privates['AppBundle\\Repository\\UserRepository'] ?? $container->getUserRepositoryService()));
    }
}
