<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHwiOauth_Security_OauthUtilsService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'hwi_oauth.security.oauth_utils' shared service.
     *
     * @return \HWI\Bundle\OAuthBundle\Security\OAuthUtils
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/hwi/oauth-bundle/src/Security/OAuthUtils.php';

        $a = ($container->services['jms_serializer.authorization_checker'] ?? $container->getJmsSerializer_AuthorizationCheckerService());

        if (isset($container->privates['hwi_oauth.security.oauth_utils'])) {
            return $container->privates['hwi_oauth.security.oauth_utils'];
        }

        $container->privates['hwi_oauth.security.oauth_utils'] = $instance = new \HWI\Bundle\OAuthBundle\Security\OAuthUtils(($container->privates['security.http_utils'] ?? $container->load('getSecurity_HttpUtilsService')), $a, true, 'IS_AUTHENTICATED_REMEMBERED');

        $instance->addResourceOwnerMap(($container->services['hwi_oauth.resource_ownermap.main'] ?? $container->load('getHwiOauth_ResourceOwnermap_MainService')));

        return $instance;
    }
}
