<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHttplug_ClientService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'httplug.client' shared service.
     *
     * @return \Http\Client\Common\PluginClient
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/psr/http-client/src/ClientInterface.php';
        include_once \dirname(__DIR__, 6).'/vendor/php-http/httplug/src/HttpClient.php';
        include_once \dirname(__DIR__, 6).'/vendor/php-http/httplug/src/HttpAsyncClient.php';
        include_once \dirname(__DIR__, 6).'/vendor/php-http/client-common/src/PluginClient.php';

        return $container->services['httplug.client'] = ($container->privates['Http\\Client\\Common\\PluginClientFactory'] ?? $container->getPluginClientFactoryService())->createClient(($container->privates['httplug.client.default.client'] ?? $container->load('getHttplug_Client_Default_ClientService')), [], ['client_name' => 'default']);
    }
}
