<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHwiOauth_ResourceOwner_AzureService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'hwi_oauth.resource_owner.azure' shared service.
     *
     * @return \HWI\Bundle\OAuthBundle\OAuth\ResourceOwner\AzureResourceOwner
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/hwi/oauth-bundle/src/OAuth/ResourceOwnerInterface.php';
        include_once \dirname(__DIR__, 6).'/vendor/hwi/oauth-bundle/src/OAuth/ResourceOwner/AbstractResourceOwner.php';
        include_once \dirname(__DIR__, 6).'/vendor/hwi/oauth-bundle/src/OAuth/ResourceOwner/GenericOAuth2ResourceOwner.php';
        include_once \dirname(__DIR__, 6).'/vendor/hwi/oauth-bundle/src/OAuth/ResourceOwner/AzureResourceOwner.php';

        return $container->privates['hwi_oauth.resource_owner.azure'] = new \HWI\Bundle\OAuthBundle\OAuth\ResourceOwner\AzureResourceOwner(($container->privates['.debug.hwi_oauth.http_client'] ?? $container->get_Debug_HwiOauth_HttpClientService()), ($container->privates['security.http_utils'] ?? $container->load('getSecurity_HttpUtilsService')), ['client_id' => $container->getEnv('OAUTH_AZURE_CLIENT_ID'), 'client_secret' => $container->getEnv('OAUTH_AZURE_CLIENT_SECRET'), 'access_token_url' => $container->getEnv('OAUTH_AZURE_URL_ACCESS_TOKEN'), 'authorization_url' => $container->getEnv('OAUTH_AZURE_URL_AUTHORIZATION'), 'scope' => $container->getEnv('OAUTH_AZURE_OPTION_SCOPE'), 'options' => ['application' => 'common'], 'paths' => []], 'azure', ($container->privates['hwi_oauth.storage.session'] ?? $container->load('getHwiOauth_Storage_SessionService')));
    }
}
