<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHwiOauth_ResourceOwnermapLocatorService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'hwi_oauth.resource_ownermap_locator' shared service.
     *
     * @return \HWI\Bundle\OAuthBundle\Security\Http\ResourceOwnerMapLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/hwi/oauth-bundle/src/Security/Http/ResourceOwnerMapLocator.php';

        $container->privates['hwi_oauth.resource_ownermap_locator'] = $instance = new \HWI\Bundle\OAuthBundle\Security\Http\ResourceOwnerMapLocator();

        $instance->set('main', ($container->services['hwi_oauth.resource_ownermap.main'] ?? $container->load('getHwiOauth_ResourceOwnermap_MainService')));

        return $instance;
    }
}
