<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHtmlControllerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'AppBundle\Controller\Element\SmartBlock\HtmlController' shared autowired service.
     *
     * @return \AppBundle\Controller\Element\SmartBlock\HtmlController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/wirdesign-communication-ag/wirhub/Controller/Element/SmartBlock/HtmlController.php';

        return $container->services['AppBundle\\Controller\\Element\\SmartBlock\\HtmlController'] = new \AppBundle\Controller\Element\SmartBlock\HtmlController(($container->privates['AppBundle\\Repository\\ElementRepository'] ?? $container->getElementRepositoryService()), ($container->privates['AppBundle\\Services\\Element\\ElementFormService'] ?? $container->load('getElementFormServiceService')), ($container->privates['AppBundle\\Services\\Element\\SmartBlock\\HtmlService'] ??= new \AppBundle\Services\Element\SmartBlock\HtmlService()), ($container->privates['AppBundle\\Services\\UserService'] ?? $container->getUserServiceService()));
    }
}
