<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHwiOauth_Storage_SessionService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'hwi_oauth.storage.session' shared service.
     *
     * @return \HWI\Bundle\OAuthBundle\OAuth\RequestDataStorage\SessionStorage
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/hwi/oauth-bundle/src/OAuth/RequestDataStorageInterface.php';
        include_once \dirname(__DIR__, 6).'/vendor/hwi/oauth-bundle/src/OAuth/RequestDataStorage/SessionStorage.php';

        return $container->privates['hwi_oauth.storage.session'] = new \HWI\Bundle\OAuthBundle\OAuth\RequestDataStorage\SessionStorage(($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()));
    }
}
