<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getImportControllerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'AppBundle\Controller\Admin\User\ImportController' shared autowired service.
     *
     * @return \AppBundle\Controller\Admin\User\ImportController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/wirdesign-communication-ag/wirhub/Controller/Admin/User/ImportController.php';

        return $container->services['AppBundle\\Controller\\Admin\\User\\ImportController'] = new \AppBundle\Controller\Admin\User\ImportController(($container->privates['AppBundle\\Repository\\SpaceRepository'] ?? $container->getSpaceRepositoryService()), ($container->privates['AppBundle\\Repository\\UserRepository'] ?? $container->getUserRepositoryService()), ($container->privates['AppBundle\\Services\\ResponseService'] ?? $container->load('getResponseServiceService')), ($container->privates['AppBundle\\Services\\UserService'] ?? $container->getUserServiceService()), ($container->privates['AppBundle\\Form\\User\\ImportFormFlow'] ?? $container->load('getImportFormFlowService')));
    }
}
