<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getImportFormFlowService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'AppBundle\Form\User\ImportFormFlow' shared autowired service.
     *
     * @return \AppBundle\Form\User\ImportFormFlow
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/craue/formflow-bundle/Form/FormFlowInterface.php';
        include_once \dirname(__DIR__, 6).'/vendor/craue/formflow-bundle/Form/FormFlow.php';
        include_once \dirname(__DIR__, 6).'/vendor/wirdesign-communication-ag/wirhub/Form/User/ImportFormFlow.php';

        $container->privates['AppBundle\\Form\\User\\ImportFormFlow'] = $instance = new \AppBundle\Form\User\ImportFormFlow();

        $instance->setDataManager(($container->privates['craue.form.flow.data_manager_default'] ?? $container->load('getCraue_Form_Flow_DataManagerDefaultService')));
        $instance->setFormFactory(($container->privates['form.factory'] ?? $container->getForm_FactoryService()));
        $instance->setRequestStack(($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()));
        if ($container->has('event_dispatcher')) {
            $instance->setEventDispatcher(($container->services['event_dispatcher'] ?? $container->getEventDispatcherService()));
        }

        return $instance;
    }
}
