<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInspirationService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.wImp64e.AppBundle\Entity\SmartTool\Inspiration\Inspiration' shared service.
     *
     * @return \AppBundle\Entity\SmartTool\Inspiration\Inspiration
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.wImp64e": it needs an instance of "AppBundle\\Entity\\SmartTool\\Inspiration\\Inspiration" but this type has been excluded in "config/services.yaml".');
    }
}
