<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInspirationControllerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'AppBundle\Controller\Element\SmartBlock\InspirationController' shared autowired service.
     *
     * @return \AppBundle\Controller\Element\SmartBlock\InspirationController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/wirdesign-communication-ag/wirhub/Controller/Element/SmartBlock/InspirationController.php';

        return $container->services['AppBundle\\Controller\\Element\\SmartBlock\\InspirationController'] = new \AppBundle\Controller\Element\SmartBlock\InspirationController(($container->privates['form.factory'] ?? $container->getForm_FactoryService()), ($container->privates['AppBundle\\Router\\PersistentQueryRouter'] ?? $container->getPersistentQueryRouterService()), ($container->services['translator'] ?? $container->getTranslatorService()), ($container->privates['AppBundle\\Repository\\SmartTool\\Inspiration\\EyeCatcherRepository'] ?? $container->getEyeCatcherRepositoryService()), ($container->privates['AppBundle\\Repository\\SmartTool\\Inspiration\\InspirationRepository'] ?? $container->getInspirationRepositoryService()), ($container->privates['AppBundle\\Repository\\SmartTool\\Inspiration\\InspirationTagTypeRepository'] ?? $container->getInspirationTagTypeRepositoryService()), ($container->privates['AppBundle\\Services\\Element\\SmartBlock\\InspirationService'] ?? $container->load('getInspirationServiceService')), ($container->privates['AppBundle\\Services\\UserService'] ?? $container->getUserServiceService()));
    }
}
