<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getIconListSubscriberService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'AppBundle\EventSubscriber\Element\IconListSubscriber' shared autowired service.
     *
     * @return \AppBundle\EventSubscriber\Element\IconListSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/wirdesign-communication-ag/wirhub/EventSubscriber/Element/IconListSubscriber.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService());

        if (isset($container->privates['AppBundle\\EventSubscriber\\Element\\IconListSubscriber'])) {
            return $container->privates['AppBundle\\EventSubscriber\\Element\\IconListSubscriber'];
        }

        return $container->privates['AppBundle\\EventSubscriber\\Element\\IconListSubscriber'] = new \AppBundle\EventSubscriber\Element\IconListSubscriber(($container->privates['AppBundle\\Repository\\SmartBlock\\IconList\\IconRepository'] ?? $container->getIconRepositoryService()), ($container->privates['AppBundle\\Repository\\SmartBlock\\IconList\\IconFileRepository'] ?? $container->getIconFileRepositoryService()), $a);
    }
}
