<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getIconListDownloadCommandService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'AppBundle\Command\Element\IconListDownloadCommand' shared autowired service.
     *
     * @return \AppBundle\Command\Element\IconListDownloadCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 6).'/vendor/wirdesign-communication-ag/wirhub/Command/Element/IconListDownloadCommand.php';

        $container->privates['AppBundle\\Command\\Element\\IconListDownloadCommand'] = $instance = new \AppBundle\Command\Element\IconListDownloadCommand(($container->privates['AppBundle\\Repository\\SmartBlock\\IconDownloadRepository'] ?? $container->getIconDownloadRepositoryService()), ($container->privates['AppBundle\\Repository\\SmartBlock\\IconList\\IconRepository'] ?? $container->getIconRepositoryService()), ($container->privates['AppBundle\\Services\\Element\\SmartBlock\\IconListService'] ?? $container->getIconListServiceService()), ($container->privates['AppBundle\\Services\\FileService'] ?? $container->getFileServiceService()), ($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()));

        $instance->setName('app:element:iconlistdownload');

        return $instance;
    }
}
