<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInspirationSubscriberService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'AppBundle\EventSubscriber\Tool\InspirationSubscriber' shared autowired service.
     *
     * @return \AppBundle\EventSubscriber\Tool\InspirationSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/wirdesign-communication-ag/wirhub/EventSubscriber/Tool/InspirationSubscriber.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService());

        if (isset($container->privates['AppBundle\\EventSubscriber\\Tool\\InspirationSubscriber'])) {
            return $container->privates['AppBundle\\EventSubscriber\\Tool\\InspirationSubscriber'];
        }

        return $container->privates['AppBundle\\EventSubscriber\\Tool\\InspirationSubscriber'] = new \AppBundle\EventSubscriber\Tool\InspirationSubscriber($a, ($container->privates['AppBundle\\Repository\\SmartTool\\Inspiration\\InspirationRepository'] ?? $container->getInspirationRepositoryService()));
    }
}
