<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getIconTagService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.HUJb58l.AppBundle\Entity\SmartBlock\IconTag' shared service.
     *
     * @return \AppBundle\Entity\SmartBlock\IconTag
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.HUJb58l": it needs an instance of "AppBundle\\Entity\\SmartBlock\\IconTag" but this type has been excluded in "config/services.yaml".');
    }
}
