<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getItemInterface5Service extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'Knp\Menu\ItemInterface_5' shared service.
     *
     * @return \Knp\Menu\MenuItem
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/knplabs/knp-menu/src/Knp/Menu/ItemInterface.php';
        include_once \dirname(__DIR__, 6).'/vendor/knplabs/knp-menu/src/Knp/Menu/MenuItem.php';

        $a = ($container->privates['AppBundle\\Component\\Menu\\Builder'] ?? $container->load('getBuilderService'));

        if (isset($container->privates['Knp\\Menu\\ItemInterface_5'])) {
            return $container->privates['Knp\\Menu\\ItemInterface_5'];
        }

        return $container->privates['Knp\\Menu\\ItemInterface_5'] = $a->createMenu(($container->privates['AppBundle\\Component\\Menu\\Matcher'] ?? $container->load('getMatcherService')), 'AppBundle\\Domain\\Events\\Menu\\SettingsMenuEvent');
    }
}
