<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInspirationCommentRepositoryService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'AppBundle\Repository\SmartTool\Inspiration\InspirationCommentRepository' shared autowired service.
     *
     * @return \AppBundle\Repository\SmartTool\Inspiration\InspirationCommentRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/wirdesign-communication-ag/wirhub/Repository/SmartTool/Inspiration/InspirationCommentRepository.php';

        return $container->privates['AppBundle\\Repository\\SmartTool\\Inspiration\\InspirationCommentRepository'] = new \AppBundle\Repository\SmartTool\Inspiration\InspirationCommentRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
