<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInternalLinkFormTypeService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'AppBundle\Form\InternalLinkFormType' shared autowired service.
     *
     * @return \AppBundle\Form\InternalLinkFormType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 6).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 6).'/vendor/wirdesign-communication-ag/wirhub/Form/InternalLinkFormType.php';

        $a = ($container->privates['AppBundle\\Services\\SpaceService'] ?? $container->getSpaceServiceService());

        if (isset($container->privates['AppBundle\\Form\\InternalLinkFormType'])) {
            return $container->privates['AppBundle\\Form\\InternalLinkFormType'];
        }

        return $container->privates['AppBundle\\Form\\InternalLinkFormType'] = new \AppBundle\Form\InternalLinkFormType($a);
    }
}
