<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLogServiceService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'AppBundle\Services\LogService' shared autowired service.
     *
     * @return \AppBundle\Services\LogService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/wirdesign-communication-ag/wirhub/Services/LogService.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService());

        if (isset($container->privates['AppBundle\\Services\\LogService'])) {
            return $container->privates['AppBundle\\Services\\LogService'];
        }

        return $container->privates['AppBundle\\Services\\LogService'] = new \AppBundle\Services\LogService($a, ($container->privates['monolog.logger'] ?? $container->getMonolog_LoggerService()), ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()), ($container->privates['AppBundle\\Repository\\LogRepository'] ?? $container->getLogRepositoryService()));
    }
}
