<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLocaleService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.bnW4n5X.AppBundle\Entity\Setting\Locale' shared service.
     *
     * @return \AppBundle\Entity\Setting\Locale
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.bnW4n5X": it needs an instance of "AppBundle\\Entity\\Setting\\Locale" but this type has been excluded in "config/services.yaml".');
    }
}
