<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLoginControllerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'HWI\Bundle\OAuthBundle\Controller\LoginController' shared service.
     *
     * @return \HWI\Bundle\OAuthBundle\Controller\LoginController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/hwi/oauth-bundle/src/Controller/LoginController.php';

        return $container->services['HWI\\Bundle\\OAuthBundle\\Controller\\LoginController'] = new \HWI\Bundle\OAuthBundle\Controller\LoginController(($container->privates['security.authentication_utils'] ?? $container->load('getSecurity_AuthenticationUtilsService')), ($container->services['router'] ?? $container->getRouterService()), ($container->services['jms_serializer.authorization_checker'] ?? $container->getJmsSerializer_AuthorizationCheckerService()), ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()), ($container->privates['twig'] ?? $container->getTwigService()), true, 'IS_AUTHENTICATED_REMEMBERED');
    }
}
