<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLinkFormTypeService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'AppBundle\Form\Element\LinkFormType' shared autowired service.
     *
     * @return \AppBundle\Form\Element\LinkFormType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 6).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 6).'/vendor/wirdesign-communication-ag/wirhub/Form/Element/LinkFormType.php';

        $a = ($container->privates['AppBundle\\Services\\Category\\LinkService'] ?? $container->load('getLinkServiceService'));

        if (isset($container->privates['AppBundle\\Form\\Element\\LinkFormType'])) {
            return $container->privates['AppBundle\\Form\\Element\\LinkFormType'];
        }

        return $container->privates['AppBundle\\Form\\Element\\LinkFormType'] = new \AppBundle\Form\Element\LinkFormType($a);
    }
}
