<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getManageControllerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'AppBundle\Controller\Admin\User\ManageController' shared autowired service.
     *
     * @return \AppBundle\Controller\Admin\User\ManageController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/wirdesign-communication-ag/wirhub/Controller/Admin/User/ManageController.php';

        return $container->services['AppBundle\\Controller\\Admin\\User\\ManageController'] = new \AppBundle\Controller\Admin\User\ManageController(($container->privates['AppBundle\\Repository\\UserRepository'] ?? $container->getUserRepositoryService()), ($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()), ($container->services['event_dispatcher'] ?? $container->getEventDispatcherService()), ($container->privates['form.factory'] ?? $container->getForm_FactoryService()), ($container->privates['AppBundle\\Services\\ResponseService'] ?? $container->load('getResponseServiceService')), ($container->privates['AppBundle\\Services\\SnackbarService'] ?? $container->load('getSnackbarServiceService')), ($container->services['translator'] ?? $container->getTranslatorService()), ($container->privates['AppBundle\\Services\\UserService'] ?? $container->getUserServiceService()), ($container->privates['AppBundle\\Services\\UserMailService'] ?? $container->load('getUserMailServiceService')));
    }
}
