<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMenuAsideControllerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'AppBundle\Controller\Components\MenuAsideController' shared autowired service.
     *
     * @return \AppBundle\Controller\Components\MenuAsideController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/wirdesign-communication-ag/wirhub/Controller/Components/MenuAsideController.php';

        return $container->services['AppBundle\\Controller\\Components\\MenuAsideController'] = new \AppBundle\Controller\Components\MenuAsideController(($container->privates['AppBundle\\Repository\\Component\\MenuAside\\CustomLinkRepository'] ?? $container->getCustomLinkRepositoryService()), ($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()), ($container->privates['AppBundle\\Services\\Setting\\LocaleService'] ?? $container->getLocaleServiceService()), ($container->privates['form.factory'] ?? $container->getForm_FactoryService()));
    }
}
