<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMediaCockpitControllerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'AppBundle\Controller\Feature\Connection\MediaCockpitController' shared autowired service.
     *
     * @return \AppBundle\Controller\Feature\Connection\MediaCockpitController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/wirdesign-communication-ag/wirhub/Controller/Feature/Connection/MediaCockpitController.php';

        return $container->services['AppBundle\\Controller\\Feature\\Connection\\MediaCockpitController'] = new \AppBundle\Controller\Feature\Connection\MediaCockpitController(($container->privates['AppBundle\\Repository\\Connection\\Mediacockpit\\CollectionRepository'] ?? $container->getCollectionRepositoryService()), ($container->privates['AppBundle\\Services\\Feature\\Connection\\MediacockpitService'] ?? $container->getMediacockpitServiceService()), ($container->services['knp_paginator'] ?? $container->load('getKnpPaginatorService')));
    }
}
