<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMetricsCleanUpCronjobSubscriberService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'AppBundle\EventSubscriber\Cronjob\MetricsCleanUpCronjobSubscriber' shared autowired service.
     *
     * @return \AppBundle\EventSubscriber\Cronjob\MetricsCleanUpCronjobSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/wirdesign-communication-ag/wirhub/Component/Interfaces/IsCronjobEventSubscriberInterface.php';
        include_once \dirname(__DIR__, 6).'/vendor/wirdesign-communication-ag/wirhub/EventSubscriber/Cronjob/MetricsCleanUpCronjobSubscriber.php';

        $a = ($container->privates['AppBundle\\Services\\System\\CronjobService'] ?? $container->getCronjobServiceService());

        if (isset($container->privates['AppBundle\\EventSubscriber\\Cronjob\\MetricsCleanUpCronjobSubscriber'])) {
            return $container->privates['AppBundle\\EventSubscriber\\Cronjob\\MetricsCleanUpCronjobSubscriber'];
        }
        $b = ($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService());

        if (isset($container->privates['AppBundle\\EventSubscriber\\Cronjob\\MetricsCleanUpCronjobSubscriber'])) {
            return $container->privates['AppBundle\\EventSubscriber\\Cronjob\\MetricsCleanUpCronjobSubscriber'];
        }

        return $container->privates['AppBundle\\EventSubscriber\\Cronjob\\MetricsCleanUpCronjobSubscriber'] = new \AppBundle\EventSubscriber\Cronjob\MetricsCleanUpCronjobSubscriber($a, $b, ($container->privates['AppBundle\\Repository\\UserRepository'] ?? $container->getUserRepositoryService()), ($container->privates['AppBundle\\Repository\\Metrics\\CategoryByUserRepository'] ?? $container->getCategoryByUserRepositoryService()));
    }
}
