<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMatcherService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'AppBundle\Component\Menu\Matcher' shared autowired service.
     *
     * @return \AppBundle\Component\Menu\Matcher
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/wirdesign-communication-ag/wirhub/Component/Menu/Matcher.php';

        return $container->privates['AppBundle\\Component\\Menu\\Matcher'] = new \AppBundle\Component\Menu\Matcher(($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()));
    }
}
