<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMenuServiceService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'AppBundle\Services\System\MenuService' shared autowired service.
     *
     * @return \AppBundle\Services\System\MenuService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/wirdesign-communication-ag/wirhub/Services/System/MenuService.php';

        return $container->privates['AppBundle\\Services\\System\\MenuService'] = new \AppBundle\Services\System\MenuService(($container->services['event_dispatcher'] ?? $container->getEventDispatcherService()), ($container->services['knp_menu.factory'] ?? $container->load('getKnpMenu_FactoryService')), ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()));
    }
}
