<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMailServiceService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'AppBundle\Services\MailService' shared autowired service.
     *
     * @return \AppBundle\Services\MailService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/wirdesign-communication-ag/wirhub/Services/MailService.php';

        $a = ($container->privates['mailer.mailer'] ?? $container->load('getMailer_MailerService'));

        if (isset($container->privates['AppBundle\\Services\\MailService'])) {
            return $container->privates['AppBundle\\Services\\MailService'];
        }
        $b = ($container->privates['AppBundle\\Services\\LogService'] ?? $container->load('getLogServiceService'));

        if (isset($container->privates['AppBundle\\Services\\MailService'])) {
            return $container->privates['AppBundle\\Services\\MailService'];
        }

        return $container->privates['AppBundle\\Services\\MailService'] = new \AppBundle\Services\MailService($a, ($container->privates['security.token_storage'] ?? $container->getSecurity_TokenStorageService()), ($container->privates['AppBundle\\Repository\\ConfigRepository'] ?? $container->getConfigRepositoryService()), $b);
    }
}
