<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNewsTranslationRepositoryService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'AppBundle\Repository\Setting\Feature\NewsTranslationRepository' shared autowired service.
     *
     * @return \AppBundle\Repository\Setting\Feature\NewsTranslationRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/wirdesign-communication-ag/wirhub/Repository/Setting/Feature/NewsTranslationRepository.php';

        return $container->privates['AppBundle\\Repository\\Setting\\Feature\\NewsTranslationRepository'] = new \AppBundle\Repository\Setting\Feature\NewsTranslationRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
