<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNewsServiceService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'AppBundle\Services\Setting\Feature\NewsService' shared autowired service.
     *
     * @return \AppBundle\Services\Setting\Feature\NewsService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/wirdesign-communication-ag/wirhub/Services/Setting/Feature/NewsService.php';

        $a = ($container->privates['AppBundle\\Repository\\Setting\\Feature\\NewsRepository'] ?? $container->getNewsRepositoryService());

        if (isset($container->privates['AppBundle\\Services\\Setting\\Feature\\NewsService'])) {
            return $container->privates['AppBundle\\Services\\Setting\\Feature\\NewsService'];
        }
        $b = ($container->privates['AppBundle\\Services\\UserService'] ?? $container->getUserServiceService());

        if (isset($container->privates['AppBundle\\Services\\Setting\\Feature\\NewsService'])) {
            return $container->privates['AppBundle\\Services\\Setting\\Feature\\NewsService'];
        }
        $c = ($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService());

        if (isset($container->privates['AppBundle\\Services\\Setting\\Feature\\NewsService'])) {
            return $container->privates['AppBundle\\Services\\Setting\\Feature\\NewsService'];
        }

        return $container->privates['AppBundle\\Services\\Setting\\Feature\\NewsService'] = new \AppBundle\Services\Setting\Feature\NewsService($a, $b, ($container->privates['AppBundle\\Services\\Setting\\LocaleService'] ?? $container->getLocaleServiceService()), $c);
    }
}
