<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNewsCategoryService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.nfU5iCm.AppBundle\Entity\Setting\Feature\NewsCategory' shared service.
     *
     * @return \AppBundle\Entity\Setting\Feature\NewsCategory
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.nfU5iCm": it needs an instance of "AppBundle\\Entity\\Setting\\Feature\\NewsCategory" but this type has been excluded in "config/services.yaml".');
    }
}
