<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNewsController2Service extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'AppBundle\Controller\Settings\Feature\NewsController' shared autowired service.
     *
     * @return \AppBundle\Controller\Settings\Feature\NewsController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/wirdesign-communication-ag/wirhub/Controller/Settings/Feature/NewsController.php';

        return $container->services['AppBundle\\Controller\\Settings\\Feature\\NewsController'] = new \AppBundle\Controller\Settings\Feature\NewsController(($container->privates['AppBundle\\Repository\\Setting\\Feature\\NewsRepository'] ?? $container->getNewsRepositoryService()), ($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()), ($container->privates['AppBundle\\Services\\FileService'] ?? $container->getFileServiceService()), ($container->privates['form.factory'] ?? $container->getForm_FactoryService()), ($container->privates['AppBundle\\Services\\Setting\\LocaleService'] ?? $container->getLocaleServiceService()), ($container->privates['AppBundle\\Services\\Setting\\Feature\\NewsService'] ?? $container->load('getNewsServiceService')), ($container->services['knp_paginator'] ?? $container->load('getKnpPaginatorService')), ($container->privates['AppBundle\\Services\\ResponseService'] ?? $container->load('getResponseServiceService')), ($container->privates['AppBundle\\Services\\SnackbarService'] ?? $container->load('getSnackbarServiceService')));
    }
}
