<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getORMSqliteDatabaseToolService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'Liip\TestFixturesBundle\Services\DatabaseTools\ORMSqliteDatabaseTool' shared service.
     *
     * @return \Liip\TestFixturesBundle\Services\DatabaseTools\ORMSqliteDatabaseTool
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/liip/test-fixtures-bundle/src/Services/DatabaseTools/AbstractDatabaseTool.php';
        include_once \dirname(__DIR__, 6).'/vendor/liip/test-fixtures-bundle/src/Services/DatabaseTools/ORMDatabaseTool.php';
        include_once \dirname(__DIR__, 6).'/vendor/liip/test-fixtures-bundle/src/Services/DatabaseTools/ORMSqliteDatabaseTool.php';

        return $container->privates['Liip\\TestFixturesBundle\\Services\\DatabaseTools\\ORMSqliteDatabaseTool'] = new \Liip\TestFixturesBundle\Services\DatabaseTools\ORMSqliteDatabaseTool($container, ($container->services['Liip\\TestFixturesBundle\\Services\\FixturesLoaderFactory'] ?? $container->load('getFixturesLoaderFactoryService')));
    }
}
