<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOktaUserDataConnectorService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'AppBundle\Component\Security\OktaUserDataConnector' shared autowired service.
     *
     * @return \AppBundle\Component\Security\OktaUserDataConnector
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/wirdesign-communication-ag/wirhub/Component/Security/UserDataConnectorInterface.php';
        include_once \dirname(__DIR__, 6).'/vendor/wirdesign-communication-ag/wirhub/Component/Security/OktaUserDataConnector.php';

        return $container->privates['AppBundle\\Component\\Security\\OktaUserDataConnector'] = new \AppBundle\Component\Security\OktaUserDataConnector();
    }
}
