<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOAuthProviderService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'AppBundle\Component\Security\OAuthProvider' shared autowired service.
     *
     * @return \AppBundle\Component\Security\OAuthProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/symfony/security-core/User/UserProviderInterface.php';
        include_once \dirname(__DIR__, 6).'/vendor/hwi/oauth-bundle/src/Connect/AccountConnectorInterface.php';
        include_once \dirname(__DIR__, 6).'/vendor/hwi/oauth-bundle/src/Security/Core/User/OAuthAwareUserProviderInterface.php';
        include_once \dirname(__DIR__, 6).'/vendor/wirdesign-communication-ag/wirhub/Component/Security/OAuthProvider.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService());

        if (isset($container->privates['AppBundle\\Component\\Security\\OAuthProvider'])) {
            return $container->privates['AppBundle\\Component\\Security\\OAuthProvider'];
        }
        $b = ($container->privates['AppBundle\\Services\\SpaceService'] ?? $container->getSpaceServiceService());

        if (isset($container->privates['AppBundle\\Component\\Security\\OAuthProvider'])) {
            return $container->privates['AppBundle\\Component\\Security\\OAuthProvider'];
        }
        $c = ($container->privates['AppBundle\\Services\\UserService'] ?? $container->getUserServiceService());

        if (isset($container->privates['AppBundle\\Component\\Security\\OAuthProvider'])) {
            return $container->privates['AppBundle\\Component\\Security\\OAuthProvider'];
        }

        return $container->privates['AppBundle\\Component\\Security\\OAuthProvider'] = new \AppBundle\Component\Security\OAuthProvider($a, ($container->privates['property_accessor'] ?? $container->load('getPropertyAccessorService')), ($container->privates['AppBundle\\Component\\Security\\ChainUserDataConnector'] ?? $container->load('getChainUserDataConnectorService')), ($container->privates['AppBundle\\Repository\\ConfigRepository'] ?? $container->getConfigRepositoryService()), ($container->privates['AppBundle\\Repository\\UserRepository'] ?? $container->getUserRepositoryService()), $b, $c);
    }
}
