<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPatternControllerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'AppBundle\Controller\Element\SmartBlock\PatternController' shared autowired service.
     *
     * @return \AppBundle\Controller\Element\SmartBlock\PatternController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/wirdesign-communication-ag/wirhub/Controller/Element/SmartBlock/PatternController.php';

        return $container->services['AppBundle\\Controller\\Element\\SmartBlock\\PatternController'] = new \AppBundle\Controller\Element\SmartBlock\PatternController(($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()), ($container->privates['form.factory'] ?? $container->getForm_FactoryService()), ($container->privates['AppBundle\\Router\\PersistentQueryRouter'] ?? $container->getPersistentQueryRouterService()), ($container->privates['AppBundle\\Services\\UserService'] ?? $container->getUserServiceService()), ($container->privates['AppBundle\\Repository\\ElementRepository'] ?? $container->getElementRepositoryService()), ($container->privates['AppBundle\\Repository\\Setting\\StyleRepository'] ?? $container->load('getStyleRepositoryService')));
    }
}
