<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPositionGlobalEventSubscriberService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'AppBundle\EventSubscriber\Category\PositionGlobalEventSubscriber' shared autowired service.
     *
     * @return \AppBundle\EventSubscriber\Category\PositionGlobalEventSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/wirdesign-communication-ag/wirhub/EventSubscriber/Category/PositionGlobalEventSubscriber.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService());

        if (isset($container->privates['AppBundle\\EventSubscriber\\Category\\PositionGlobalEventSubscriber'])) {
            return $container->privates['AppBundle\\EventSubscriber\\Category\\PositionGlobalEventSubscriber'];
        }
        $b = ($container->privates['AppBundle\\Repository\\CategoryRepository'] ?? $container->getCategoryRepositoryService());

        if (isset($container->privates['AppBundle\\EventSubscriber\\Category\\PositionGlobalEventSubscriber'])) {
            return $container->privates['AppBundle\\EventSubscriber\\Category\\PositionGlobalEventSubscriber'];
        }

        return $container->privates['AppBundle\\EventSubscriber\\Category\\PositionGlobalEventSubscriber'] = new \AppBundle\EventSubscriber\Category\PositionGlobalEventSubscriber($a, $b);
    }
}
