<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPatternController2Service extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'AppBundle\Controller\Settings\PatternController' shared autowired service.
     *
     * @return \AppBundle\Controller\Settings\PatternController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/wirdesign-communication-ag/wirhub/Controller/Settings/PatternController.php';

        return $container->services['AppBundle\\Controller\\Settings\\PatternController'] = new \AppBundle\Controller\Settings\PatternController(\dirname(__DIR__, 6), ($container->privates['AppBundle\\Repository\\Setting\\FontRepository'] ?? $container->getFontRepositoryService()), ($container->privates['AppBundle\\Repository\\Setting\\SourceRepository'] ?? $container->getSourceRepositoryService()), ($container->privates['AppBundle\\Repository\\Setting\\StyleRepository'] ?? $container->load('getStyleRepositoryService')), ($container->privates['AppBundle\\Services\\Vendor\\DoctrineService'] ?? $container->load('getDoctrineServiceService')), ($container->privates['AppBundle\\Services\\FileService'] ?? $container->getFileServiceService()), ($container->privates['form.factory'] ?? $container->getForm_FactoryService()), ($container->privates['AppBundle\\Services\\ResponseService'] ?? $container->load('getResponseServiceService')), ($container->privates['AppBundle\\Services\\UserService'] ?? $container->getUserServiceService()));
    }
}
