<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getQrCodeService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.5k.PWdv.AppBundle\Entity\myHub\QrCode' shared service.
     *
     * @return \AppBundle\Entity\myHub\QrCode
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.5k.PWdv": it needs an instance of "AppBundle\\Entity\\myHub\\QrCode" but this type has been excluded in "config/services.yaml".');
    }
}
