<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRouteVoterService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'AppBundle\Component\Menu\RouteVoter' shared service.
     *
     * @return \AppBundle\Component\Menu\RouteVoter
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/knplabs/knp-menu/src/Knp/Menu/Matcher/Voter/VoterInterface.php';
        include_once \dirname(__DIR__, 6).'/vendor/wirdesign-communication-ag/wirhub/Component/Menu/RouteVoter.php';

        return $container->privates['AppBundle\\Component\\Menu\\RouteVoter'] = new \AppBundle\Component\Menu\RouteVoter(($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()));
    }
}
