<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSwitchToDefaultUserVoterService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'AppBundle\Security\SwitchToDefaultUserVoter' shared autowired service.
     *
     * @return \AppBundle\Security\SwitchToDefaultUserVoter
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/symfony/security-core/Authorization/Voter/VoterInterface.php';
        include_once \dirname(__DIR__, 6).'/vendor/symfony/security-core/Authorization/Voter/CacheableVoterInterface.php';
        include_once \dirname(__DIR__, 6).'/vendor/symfony/security-core/Authorization/Voter/Voter.php';
        include_once \dirname(__DIR__, 6).'/vendor/wirdesign-communication-ag/wirhub/Security/SwitchToDefaultUserVoter.php';

        return $container->privates['AppBundle\\Security\\SwitchToDefaultUserVoter'] = new \AppBundle\Security\SwitchToDefaultUserVoter();
    }
}
