<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSettingsMenuEventSubscriberService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'AppBundle\EventSubscriber\Menu\SettingsMenuEventSubscriber' shared autowired service.
     *
     * @return \AppBundle\EventSubscriber\Menu\SettingsMenuEventSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/wirdesign-communication-ag/wirhub/EventSubscriber/Menu/SettingsMenuEventSubscriber.php';

        $a = ($container->services['jms_serializer.authorization_checker'] ?? $container->getJmsSerializer_AuthorizationCheckerService());

        if (isset($container->privates['AppBundle\\EventSubscriber\\Menu\\SettingsMenuEventSubscriber'])) {
            return $container->privates['AppBundle\\EventSubscriber\\Menu\\SettingsMenuEventSubscriber'];
        }
        $b = ($container->privates['AppBundle\\Services\\SpaceService'] ?? $container->getSpaceServiceService());

        if (isset($container->privates['AppBundle\\EventSubscriber\\Menu\\SettingsMenuEventSubscriber'])) {
            return $container->privates['AppBundle\\EventSubscriber\\Menu\\SettingsMenuEventSubscriber'];
        }

        return $container->privates['AppBundle\\EventSubscriber\\Menu\\SettingsMenuEventSubscriber'] = new \AppBundle\EventSubscriber\Menu\SettingsMenuEventSubscriber(($container->privates['AppBundle\\Repository\\ConfigRepository'] ?? $container->getConfigRepositoryService()), $a, $b);
    }
}
