<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getScriptControllerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'AppBundle\Controller\Asset\ScriptController' shared autowired service.
     *
     * @return \AppBundle\Controller\Asset\ScriptController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/wirdesign-communication-ag/wirhub/Controller/Asset/ScriptController.php';

        return $container->services['AppBundle\\Controller\\Asset\\ScriptController'] = new \AppBundle\Controller\Asset\ScriptController(\dirname(__DIR__, 6), ($container->services['event_dispatcher'] ?? $container->getEventDispatcherService()), ($container->privates['twig'] ?? $container->getTwigService()));
    }
}
