<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSystemEventSubscriberService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'AppBundle\EventSubscriber\SystemEventSubscriber' shared autowired service.
     *
     * @return \AppBundle\EventSubscriber\SystemEventSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/wirdesign-communication-ag/wirhub/EventSubscriber/SystemEventSubscriber.php';

        return $container->privates['AppBundle\\EventSubscriber\\SystemEventSubscriber'] = new \AppBundle\EventSubscriber\SystemEventSubscriber();
    }
}
