<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSettingRepositoryService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'AppBundle\Repository\Dashboard\SettingRepository' shared autowired service.
     *
     * @return \AppBundle\Repository\Dashboard\SettingRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/wirdesign-communication-ag/wirhub/Repository/Dashboard/SettingRepository.php';

        return $container->privates['AppBundle\\Repository\\Dashboard\\SettingRepository'] = new \AppBundle\Repository\Dashboard\SettingRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
