<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getShortLinkService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.nOoSw_R.AppBundle\Entity\ShortLink' shared service.
     *
     * @return \AppBundle\Entity\ShortLink
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.nOoSw_R": it needs an instance of "AppBundle\\Entity\\ShortLink" but this type has been excluded in "config/services.yaml".');
    }
}
