<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getScormControllerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'AppBundle\Controller\Element\SmartBlock\ScormController' shared autowired service.
     *
     * @return \AppBundle\Controller\Element\SmartBlock\ScormController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/wirdesign-communication-ag/wirhub/Controller/Element/SmartBlock/ScormController.php';
        include_once \dirname(__DIR__, 6).'/vendor/wirdesign-communication-ag/wirhub/Services/Element/SmartBlock/ScormService.php';

        return $container->services['AppBundle\\Controller\\Element\\SmartBlock\\ScormController'] = new \AppBundle\Controller\Element\SmartBlock\ScormController(\dirname(__DIR__, 6), ($container->privates['AppBundle\\Services\\Element\\SmartBlock\\ScormService'] ??= new \AppBundle\Services\Element\SmartBlock\ScormService(\dirname(__DIR__, 6))), ($container->privates['AppBundle\\Services\\UserService'] ?? $container->getUserServiceService()));
    }
}
