<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecurityControllerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'AppBundle\Controller\User\SecurityController' shared autowired service.
     *
     * @return \AppBundle\Controller\User\SecurityController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/wirdesign-communication-ag/wirhub/Controller/User/SecurityController.php';

        return $container->services['AppBundle\\Controller\\User\\SecurityController'] = new \AppBundle\Controller\User\SecurityController(($container->privates['AppBundle\\Services\\ResponseService'] ?? $container->load('getResponseServiceService')));
    }
}
