<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSliderControllerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'AppBundle\Controller\Element\SmartBlock\SliderController' shared autowired service.
     *
     * @return \AppBundle\Controller\Element\SmartBlock\SliderController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/wirdesign-communication-ag/wirhub/Controller/Element/SmartBlock/SliderController.php';

        return $container->services['AppBundle\\Controller\\Element\\SmartBlock\\SliderController'] = new \AppBundle\Controller\Element\SmartBlock\SliderController(($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()), ($container->privates['form.factory'] ?? $container->getForm_FactoryService()), ($container->privates['AppBundle\\Services\\FileService'] ?? $container->getFileServiceService()), ($container->privates['AppBundle\\Services\\Element\\SmartBlock\\SliderService'] ?? $container->load('getSliderServiceService')), ($container->privates['AppBundle\\Services\\UserService'] ?? $container->getUserServiceService()));
    }
}
