<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSetupCommandService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'AppBundle\Command\SetupCommand' shared autowired service.
     *
     * @return \AppBundle\Command\SetupCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 6).'/vendor/wirdesign-communication-ag/wirhub/Command/SetupCommand.php';

        $container->privates['AppBundle\\Command\\SetupCommand'] = $instance = new \AppBundle\Command\SetupCommand(($container->privates['AppBundle\\Repository\\SpaceRepository'] ?? $container->getSpaceRepositoryService()), ($container->privates['AppBundle\\Repository\\UserRepository'] ?? $container->getUserRepositoryService()), ($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()), ($container->privates['AppBundle\\Services\\UserService'] ?? $container->getUserServiceService()));

        $instance->setName('app:setup');

        return $instance;
    }
}
