<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecurity_Firewall_Map_Config_PublicService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'security.firewall.map.config.public' shared service.
     *
     * @return \Symfony\Bundle\SecurityBundle\Security\FirewallConfig
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/symfony/security-bundle/Security/FirewallConfig.php';

        return $container->privates['security.firewall.map.config.public'] = new \Symfony\Bundle\SecurityBundle\Security\FirewallConfig('public', 'security.user_checker', '.security.request_matcher.3HbYdvl', false, false, NULL, NULL, NULL, NULL, NULL, [], NULL, NULL);
    }
}
