<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSpaceCommandService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'AppBundle\Command\SpaceCommand' shared autowired service.
     *
     * @return \AppBundle\Command\SpaceCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 6).'/vendor/wirdesign-communication-ag/wirhub/Command/SpaceCommand.php';

        $container->privates['AppBundle\\Command\\SpaceCommand'] = $instance = new \AppBundle\Command\SpaceCommand(($container->privates['AppBundle\\Repository\\CategoryRepository'] ?? $container->getCategoryRepositoryService()), ($container->privates['AppBundle\\Repository\\DashboardRepository'] ?? $container->getDashboardRepositoryService()), ($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()), ($container->privates['AppBundle\\Services\\SpaceService'] ?? $container->getSpaceServiceService()));

        $instance->setName('app:space');

        return $instance;
    }
}
