<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSpacesEventSubscriberService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'AppBundle\EventSubscriber\Element\SpacesEventSubscriber' shared autowired service.
     *
     * @return \AppBundle\EventSubscriber\Element\SpacesEventSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/wirdesign-communication-ag/wirhub/EventSubscriber/Element/SpacesEventSubscriber.php';

        return $container->privates['AppBundle\\EventSubscriber\\Element\\SpacesEventSubscriber'] = new \AppBundle\EventSubscriber\Element\SpacesEventSubscriber(($container->privates['AppBundle\\Repository\\SmartBlock\\SpacesSpaceRepository'] ?? $container->getSpacesSpaceRepositoryService()));
    }
}
