<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecurity_LogoutListener_MainService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'security.logout_listener.main' shared service.
     *
     * @return \Symfony\Component\Security\Http\Firewall\LogoutListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/symfony/security-http/Firewall/LogoutListener.php';

        $a = ($container->privates['security.event_dispatcher.main'] ?? $container->getSecurity_EventDispatcher_MainService());

        if (isset($container->privates['security.logout_listener.main'])) {
            return $container->privates['security.logout_listener.main'];
        }

        return $container->privates['security.logout_listener.main'] = new \Symfony\Component\Security\Http\Firewall\LogoutListener(($container->privates['security.token_storage'] ?? $container->getSecurity_TokenStorageService()), ($container->privates['security.http_utils'] ?? $container->load('getSecurity_HttpUtilsService')), $a, ['csrf_parameter' => '_csrf_token', 'csrf_token_id' => 'logout', 'logout_path' => 'app_user_security_logout']);
    }
}
