<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSpacesMenuSubscriberService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'AppBundle\EventSubscriber\Menu\SpacesMenuSubscriber' shared autowired service.
     *
     * @return \AppBundle\EventSubscriber\Menu\SpacesMenuSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/wirdesign-communication-ag/wirhub/EventSubscriber/Menu/SpacesMenuSubscriber.php';

        $a = ($container->privates['AppBundle\\Services\\SpaceService'] ?? $container->getSpaceServiceService());

        if (isset($container->privates['AppBundle\\EventSubscriber\\Menu\\SpacesMenuSubscriber'])) {
            return $container->privates['AppBundle\\EventSubscriber\\Menu\\SpacesMenuSubscriber'];
        }

        return $container->privates['AppBundle\\EventSubscriber\\Menu\\SpacesMenuSubscriber'] = new \AppBundle\EventSubscriber\Menu\SpacesMenuSubscriber($a);
    }
}
