<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSnackbarServiceService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'AppBundle\Services\SnackbarService' shared autowired service.
     *
     * @return \AppBundle\Services\SnackbarService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/wirdesign-communication-ag/wirhub/Services/SnackbarService.php';

        return $container->privates['AppBundle\\Services\\SnackbarService'] = new \AppBundle\Services\SnackbarService(($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()), ($container->services['translator'] ?? $container->getTranslatorService()));
    }
}
