<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getShortLinkServiceService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'AppBundle\Services\ShortLinkService' shared autowired service.
     *
     * @return \AppBundle\Services\ShortLinkService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/wirdesign-communication-ag/wirhub/Services/ShortLinkService.php';

        return $container->privates['AppBundle\\Services\\ShortLinkService'] = new \AppBundle\Services\ShortLinkService(($container->privates['AppBundle\\Services\\UserService'] ?? $container->getUserServiceService()), ($container->privates['AppBundle\\Repository\\CategoryRepository'] ?? $container->getCategoryRepositoryService()), ($container->privates['AppBundle\\Repository\\ElementRepository'] ?? $container->getElementRepositoryService()), ($container->privates['AppBundle\\Repository\\ShortLinkRepository'] ?? $container->load('getShortLinkRepositoryService')), ($container->privates['AppBundle\\Repository\\SpaceRepository'] ?? $container->getSpaceRepositoryService()));
    }
}
