<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getToolInspirationItemFormTypeService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'AppBundle\Form\Element\SmartBlock\Inspiration\ToolInspirationItemFormType' shared autowired service.
     *
     * @return \AppBundle\Form\Element\SmartBlock\Inspiration\ToolInspirationItemFormType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 6).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 6).'/vendor/wirdesign-communication-ag/wirhub/Form/Element/SmartBlock/Inspiration/ToolInspirationItemFormType.php';

        return $container->privates['AppBundle\\Form\\Element\\SmartBlock\\Inspiration\\ToolInspirationItemFormType'] = new \AppBundle\Form\Element\SmartBlock\Inspiration\ToolInspirationItemFormType(($container->privates['AppBundle\\Repository\\SmartTool\\Inspiration\\InspirationTagTypeRepository'] ?? $container->getInspirationTagTypeRepositoryService()), ($container->privates['AppBundle\\Repository\\Setting\\LocaleRepository'] ?? $container->getLocaleRepositoryService()));
    }
}
