<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTestCommandService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'AppBundle\Command\TestCommand' shared autowired service.
     *
     * @return \AppBundle\Command\TestCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 6).'/vendor/wirdesign-communication-ag/wirhub/Command/TestCommand.php';

        $container->privates['AppBundle\\Command\\TestCommand'] = $instance = new \AppBundle\Command\TestCommand();

        $instance->setName('app:test');

        return $instance;
    }
}
