<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getToolInspirationControllerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'AppBundle\Controller\Settings\ToolInspirationController' shared autowired service.
     *
     * @return \AppBundle\Controller\Settings\ToolInspirationController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/wirdesign-communication-ag/wirhub/Controller/Settings/ToolInspirationController.php';

        return $container->services['AppBundle\\Controller\\Settings\\ToolInspirationController'] = new \AppBundle\Controller\Settings\ToolInspirationController(($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()), ($container->privates['form.factory'] ?? $container->getForm_FactoryService()), ($container->privates['AppBundle\\Repository\\SmartTool\\Inspiration\\InspirationTagTypeRepository'] ?? $container->getInspirationTagTypeRepositoryService()), ($container->privates['AppBundle\\Services\\Element\\SmartBlock\\InspirationService'] ?? $container->load('getInspirationServiceService')), ($container->privates['AppBundle\\Services\\ResponseService'] ?? $container->load('getResponseServiceService')));
    }
}
