<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTableSubscriberService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'AppBundle\EventSubscriber\Element\TableSubscriber' shared autowired service.
     *
     * @return \AppBundle\EventSubscriber\Element\TableSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/wirdesign-communication-ag/wirhub/EventSubscriber/Element/TableSubscriber.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService());

        if (isset($container->privates['AppBundle\\EventSubscriber\\Element\\TableSubscriber'])) {
            return $container->privates['AppBundle\\EventSubscriber\\Element\\TableSubscriber'];
        }

        return $container->privates['AppBundle\\EventSubscriber\\Element\\TableSubscriber'] = new \AppBundle\EventSubscriber\Element\TableSubscriber($a, ($container->privates['AppBundle\\Repository\\SmartBlock\\Table\\TableRowRepository'] ?? $container->getTableRowRepositoryService()));
    }
}
