<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTaskCommandService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'AppBundle\Command\TaskCommand' shared autowired service.
     *
     * @return \AppBundle\Command\TaskCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 6).'/vendor/wirdesign-communication-ag/wirhub/Command/TaskCommand.php';

        $container->privates['AppBundle\\Command\\TaskCommand'] = $instance = new \AppBundle\Command\TaskCommand(($container->services['doctrine'] ?? $container->getDoctrineService()), ($container->privates['AppBundle\\Services\\User\\AccessTokenService'] ?? $container->load('getAccessTokenServiceService')), ($container->privates['AppBundle\\Services\\FileService'] ?? $container->getFileServiceService()), ($container->privates['AppBundle\\Repository\\User\\AccessTokenRepository'] ?? $container->load('getAccessTokenRepositoryService')));

        $instance->setName('app:task');

        return $instance;
    }
}
