<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getThemeControllerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'AppBundle\Controller\Asset\ThemeController' shared autowired service.
     *
     * @return \AppBundle\Controller\Asset\ThemeController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/wirdesign-communication-ag/wirhub/Controller/Asset/ThemeController.php';
        include_once \dirname(__DIR__, 6).'/vendor/wirdesign-communication-ag/wirhub/Services/ThemeService.php';

        return $container->services['AppBundle\\Controller\\Asset\\ThemeController'] = new \AppBundle\Controller\Asset\ThemeController(\dirname(__DIR__, 6), ($container->privates['AppBundle\\Repository\\Setting\\ThemeRepository'] ?? $container->getThemeRepositoryService()), ($container->privates['AppBundle\\Services\\ThemeService'] ??= new \AppBundle\Services\ThemeService(\dirname(__DIR__, 6))));
    }
}
