<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTagRepositoryService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'AppBundle\Repository\File\TagRepository' shared autowired service.
     *
     * @return \AppBundle\Repository\File\TagRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/wirdesign-communication-ag/wirhub/Repository/File/TagRepository.php';

        return $container->privates['AppBundle\\Repository\\File\\TagRepository'] = new \AppBundle\Repository\File\TagRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
