<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTemplateServiceService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'AppBundle\Services\Setting\TemplateService' shared autowired service.
     *
     * @return \AppBundle\Services\Setting\TemplateService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/wirdesign-communication-ag/wirhub/Services/Setting/TemplateService.php';

        $a = ($container->privates['AppBundle\\Services\\LogService'] ?? $container->load('getLogServiceService'));

        if (isset($container->privates['AppBundle\\Services\\Setting\\TemplateService'])) {
            return $container->privates['AppBundle\\Services\\Setting\\TemplateService'];
        }

        return $container->privates['AppBundle\\Services\\Setting\\TemplateService'] = new \AppBundle\Services\Setting\TemplateService(($container->privates['AppBundle\\Repository\\Setting\\TemplateRepository'] ?? $container->load('getTemplateRepositoryService')), $a);
    }
}
