<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTemplateRepositoryService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'AppBundle\Repository\Setting\TemplateRepository' shared autowired service.
     *
     * @return \AppBundle\Repository\Setting\TemplateRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/wirdesign-communication-ag/wirhub/Repository/Setting/TemplateRepository.php';

        return $container->privates['AppBundle\\Repository\\Setting\\TemplateRepository'] = new \AppBundle\Repository\Setting\TemplateRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
