<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getThemeService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.e.0wwwZ.AppBundle\Entity\Setting\Theme' shared service.
     *
     * @return \AppBundle\Entity\Setting\Theme
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.e.0wwwZ": it needs an instance of "AppBundle\\Entity\\Setting\\Theme" but this type has been excluded in "config/services.yaml".');
    }
}
