<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getThemeServiceService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'AppBundle\Services\ThemeService' shared autowired service.
     *
     * @return \AppBundle\Services\ThemeService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/wirdesign-communication-ag/wirhub/Services/ThemeService.php';

        return $container->privates['AppBundle\\Services\\ThemeService'] = new \AppBundle\Services\ThemeService(\dirname(__DIR__, 6));
    }
}
