<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUploadControllerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'AppBundle\Controller\File\UploadController' shared autowired service.
     *
     * @return \AppBundle\Controller\File\UploadController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/wirdesign-communication-ag/wirhub/Controller/File/UploadController.php';

        return $container->services['AppBundle\\Controller\\File\\UploadController'] = new \AppBundle\Controller\File\UploadController(($container->privates['AppBundle\\Repository\\Element\\ElementFileRepository'] ?? $container->getElementFileRepositoryService()), ($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()), ($container->privates['form.factory'] ?? $container->getForm_FactoryService()), ($container->services['translator'] ?? $container->getTranslatorService()), ($container->privates['AppBundle\\Router\\PersistentQueryRouter'] ?? $container->getPersistentQueryRouterService()), ($container->privates['AppBundle\\Services\\FileService'] ?? $container->getFileServiceService()));
    }
}
