<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserFormTypeService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'AppBundle\Form\UserFormType' shared autowired service.
     *
     * @return \AppBundle\Form\UserFormType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 6).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 6).'/vendor/wirdesign-communication-ag/wirhub/Form/User/AbstractUserFormType.php';
        include_once \dirname(__DIR__, 6).'/vendor/wirdesign-communication-ag/wirhub/Form/UserFormType.php';

        $a = ($container->privates['AppBundle\\Services\\SpaceService'] ?? $container->getSpaceServiceService());

        if (isset($container->privates['AppBundle\\Form\\UserFormType'])) {
            return $container->privates['AppBundle\\Form\\UserFormType'];
        }
        $b = ($container->privates['AppBundle\\Services\\UserService'] ?? $container->getUserServiceService());

        if (isset($container->privates['AppBundle\\Form\\UserFormType'])) {
            return $container->privates['AppBundle\\Form\\UserFormType'];
        }

        return $container->privates['AppBundle\\Form\\UserFormType'] = new \AppBundle\Form\UserFormType(($container->privates['AppBundle\\Repository\\User\\GroupRepository'] ?? $container->getGroupRepositoryService()), ($container->privates['AppBundle\\Services\\Setting\\LocaleService'] ?? $container->getLocaleServiceService()), $a, $b);
    }
}
