<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserProviderService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'AppBundle\Security\UserProvider' shared autowired service.
     *
     * @return \AppBundle\Security\UserProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/symfony/security-core/User/UserProviderInterface.php';
        include_once \dirname(__DIR__, 6).'/vendor/symfony/security-core/User/PasswordUpgraderInterface.php';
        include_once \dirname(__DIR__, 6).'/vendor/wirdesign-communication-ag/wirhub/Security/UserProvider.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService());

        if (isset($container->privates['AppBundle\\Security\\UserProvider'])) {
            return $container->privates['AppBundle\\Security\\UserProvider'];
        }

        return $container->privates['AppBundle\\Security\\UserProvider'] = new \AppBundle\Security\UserProvider(($container->privates['AppBundle\\Repository\\UserRepository'] ?? $container->getUserRepositoryService()), ($container->privates['AppBundle\\Repository\\User\\AccessTokenRepository'] ?? $container->load('getAccessTokenRepositoryService')), $a);
    }
}
