<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.5UfcsPE.AppBundle\Entity\User' shared service.
     *
     * @return \AppBundle\Entity\User
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.5UfcsPE": it needs an instance of "AppBundle\\Entity\\User" but this type has been excluded in "config/services.yaml".');
    }
}
