<?php

namespace ContainerZP5moeJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVideoControllerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'AppBundle\Controller\Element\SmartBlock\VideoController' shared autowired service.
     *
     * @return \AppBundle\Controller\Element\SmartBlock\VideoController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/wirdesign-communication-ag/wirhub/Controller/Element/SmartBlock/VideoController.php';

        return $container->services['AppBundle\\Controller\\Element\\SmartBlock\\VideoController'] = new \AppBundle\Controller\Element\SmartBlock\VideoController(($container->privates['AppBundle\\Services\\Element\\ElementFormService'] ?? $container->load('getElementFormServiceService')), ($container->privates['form.factory'] ?? $container->getForm_FactoryService()), ($container->privates['AppBundle\\Services\\UserService'] ?? $container->getUserServiceService()));
    }
}
