imports:
  - { resource: config_dev.yml }
  - { resource: services_test.yml }
  - { resource: '@AppBundle/Resources/config/services_test.yaml' }

framework:
  test: ~
  session:
    storage_id: session.storage.mock_file
  #profiler: { only_exceptions: false }
  profiler:
    enabled: true
    collect: false
  mailer:
    dsn: 'null://null'

web_profiler:
  toolbar: false
  intercept_redirects: false

parameters:
  locale: de
