imports:
  - { resource: config_dev.yml }
  - { resource: services_test.yml }

framework:
  test: ~
  #profiler: { only_exceptions: false }
  profiler:
    collect: false
  session:
    handler_id: session.handler.native_file
    save_path: '%env(DEV_FRAMEWORK_SESSION_SAVE_PATH)%'
  mailer:
    dsn: 'null://null'

web_profiler:
  toolbar: false
  intercept_redirects: false

parameters:
  locale: de
