name: 'CI'
on:
    pull_request:
        branches: [ 'main', 'wip/*' ]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3

            -   name: Add GitHub OAuth credentials
                run: echo '${{ secrets.COMPOSER_AUTH_JSON }}' > $GITHUB_WORKSPACE/auth.json

            -   name: Install extensions
                uses: shivammathur/setup-php@v2
                with:
                    php-version: '8.2'
                    extensions: imagick, sqlite3
                    ini-values: error_log=/home/runner/.symfony5/log/php.log

            -   name: Log some versions
                run: |
                    echo ""
                    echo "---------------------------"
                    google-chrome --version
                    echo "---------------------------"
                    php --version
                    echo "---------------------------"
                    composer --version
                    echo "---------------------------"

            -   name: Install Symfony Server
                run: wget https://get.symfony.com/cli/installer -O - | bash

            -   name: Install dependencies
                run: APP_ENV=test composer install --prefer-dist --no-progress

            -   name: Dump environment
                run: APP_ENV=test composer dump-env test

            -   name: Clear cache
                run: APP_ENV=test php bin/console cache:clear

            -   name: Recreate assets
                run: APP_ENV=test php bin/console assets:install public/

            -   name: Start Server
                run: APP_ENV=test /home/runner/.symfony5/bin/symfony server:start -d --no-tls

            -   name: Run tests
                run: chmod -R 0777 ./ && make test

            -   name: Archive debugging files
                uses: actions/upload-artifact@v3
                if: failure()
                with:
                    name: debug
                    if-no-files-found: ignore
                    path: |
                        .env.local.php
                        vendor/wirdesign-communication-ag/wirhub/build/debug/*
                        var/cache/test/*.log
                        var/cache/wdc-styleguide.db
                        var/log/*.log
                        ~/.symfony5/log/*.log