name: 'CI PHP 8.4'
on:
    pull_request:
        branches: [ 'main', 'v3.1', 'v3.1.*' ]
jobs:
    build:
        runs-on: ubuntu-latest
        container:
            image: ghcr.io/wirdesign-communication-ag/wirhub-app/test:latest
            credentials:
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
        steps:
            -   name: Load project repository
                uses: actions/checkout@v6

            -   name: Add GitHub OAuth credentials
                run: echo '${{ secrets.COMPOSER_AUTH_JSON }}' > $GITHUB_WORKSPACE/auth.json

            -   name: Install dependencies
                run: APP_ENV=test composer install --prefer-dist --no-progress --no-scripts

            -   name: Install bundle DotEnv file
                run: cp vendor/wirdesign-communication-ag/wirhub/.env.github .env.test.local

            -   name: Verify some versions
                run: |
                    echo "-- Google Chrome --"
                    google-chrome --version
                    echo "-- Chromedriver --"
                    chromedriver --version
                    echo "-- Composer --"
                    composer --version
                    echo "-- PHP --"
                    php --version

            -   name: PHP CS Fixer
                run: php vendor/bin/php-cs-fixer check --stop-on-violation --config=.php-cs-fixer.dist.php

            -   name: Prepare symfony
                run: |
                    APP_ENV=test composer dump-env test
                    APP_ENV=test php bin/console cache:clear
                    APP_ENV=test php bin/console assets:install public/
                    APP_ENV=test php bin/console doctrine:schema:update --force
                    mkdir -p var/cache/test/sessions

            -   name: Test - Lint
                run: |
                    APP_ENV=test php bin/console lint:twig templates/
                    APP_ENV=test php bin/console lint:yaml config/
                    APP_ENV=test php bin/console lint:container

            -   name: Test - PHPStan
                run: vendor/bin/phpstan analyse -c phpstan.neon

            -   name: Test - App
                run: APP_ENV=test php bin/console app:test

            -   name: Test - WebTestCase and KernelTestCase
                run: php bin/phpunit -c phpunit.xml.dist vendor/wirdesign-communication-ag/wirhub/Tests/Cases/WebAndKernel/

            -   name: Start Webserver for Panther
                run: APP_ENV=test php -S localhost:8000 -t public/ > /tmp/php-server.log 2>&1 &

            -   name: Test - PantherTestCase
                run: php bin/phpunit -c phpunit.xml.dist vendor/wirdesign-communication-ag/wirhub/Tests/Cases/Panther/

            -   name: Archive debugging files
                uses: actions/upload-artifact@v7
                if: failure()
                with:
                    name: debug
                    if-no-files-found: ignore
                    path: |
                        .env.local.php
                        var/cache/*.log
                        var/cache/test/*.log
                        var/error-screenshots/*
                        var/log/*
                        var/wdc-styleguide.db
                        vendor/wirdesign-communication-ag/wirhub/build/debug/*
