name: 'CI Prod'

on:
  pull_request:
    branches: [ 'v3.0' ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: imagick, sqlite3
          ini-values: error_log=/home/runner/.symfony5/log/php.log

      - name: Log some versions
        run: |
          echo ""
          echo "---------------------------"
          google-chrome --version
          echo "---------------------------"
          php --version
          echo "---------------------------"
          composer --version
          echo "---------------------------"

      - name: Install dependencies
        run: APP_ENV=test composer install --prefer-dist --no-progress

      - name: Install Symfony Server
        run: wget https://get.symfony.com/cli/installer -O - | bash

      - name: Start Server
        run: APP_ENV=panther /home/runner/.symfony5/bin/symfony server:start -d --no-tls

      - name: Run tests
        run: chmod -R 0755 ./ && make test-ci

      - name: Archive debugging files
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: debug
          if-no-files-found: ignore
          path: |
            build/debug
            build/coverage
            var/cache/test/*.log
            var/cache/wdc-styleguide.db
            ~/.symfony5/log/*.log

      - name: Archive coverage
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: build/coverage