name: Docker CI publish package

on:
    push:
        tags: [ 'v3.2.*', 'v3.2.*.*', 'beta-v3.2.*' ]

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: wirdesign-communication-ag/wirhub-app

jobs:
    app:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
            id-token: write

        steps:
            -   name: Checkout repository
                uses: actions/checkout@v6

            -   name: Setup Docker buildx
                uses: docker/setup-buildx-action@v4

            -   name: Log into registry ${{ env.REGISTRY }}
                if: github.event_name != 'pull_request'
                uses: docker/login-action@v4
                with:
                    registry: ${{ env.REGISTRY }}
                    username: ${{ github.actor }}
                    password: ${{ secrets.GITHUB_TOKEN }}

            -   name: Extract Docker metadata
                id: meta
                uses: docker/metadata-action@v6
                with:
                    images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
                    flavor: |
                        latest=false
                    tags: |
                        type=ref,event=tag
                        type=sha
                        type=raw,value=latest,enable=${{ startsWith(github.ref, 'refs/tags/v') && !contains(github.ref, 'beta') && !contains(github.ref, 'rc') }}

            -   name: Add GitHub OAuth credentials
                run: echo '${{ secrets.COMPOSER_AUTH_JSON }}' > ./auth.json

            -   name: Build and push Docker image
                id: build-and-push
                uses: docker/build-push-action@v7
                with:
                    context: .
                    file: build/docker/app-on-fpm/Dockerfile
                    push: ${{ github.event_name != 'pull_request' }}
                    tags: ${{ steps.meta.outputs.tags }}
                    labels: ${{ steps.meta.outputs.labels }}
                    provenance: false
                    cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:buildcache
                    cache-to: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:buildcache,mode=max,image-manifest=true,oci-mediatypes=true,ignore-error=true
